// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package mocks

import (
	"sync"

	"github.com/bitrise-io/xcelerate/internal"
)

// Ensure, that XcodeRunnerMock does implement internal.XcodeRunner.
// If this is not the case, regenerate this file with moq.
var _ internal.XcodeRunner = &XcodeRunnerMock{}

// XcodeRunnerMock is a mock implementation of internal.XcodeRunner.
//
//	func TestSomethingThatUsesXcodeRunner(t *testing.T) {
//
//		// make and configure a mocked internal.XcodeRunner
//		mockedXcodeRunner := &XcodeRunnerMock{
//			RunFunc: func(args []string) error {
//				panic("mock out the Run method")
//			},
//		}
//
//		// use mockedXcodeRunner in code that requires internal.XcodeRunner
//		// and then make assertions.
//
//	}
type XcodeRunnerMock struct {
	// RunFunc mocks the Run method.
	RunFunc func(args []string) error

	// calls tracks calls to the methods.
	calls struct {
		// Run holds details about calls to the Run method.
		Run []struct {
			// Args is the args argument value.
			Args []string
		}
	}
	lockRun sync.RWMutex
}

// Run calls RunFunc.
func (mock *XcodeRunnerMock) Run(args []string) error {
	if mock.RunFunc == nil {
		panic("XcodeRunnerMock.RunFunc: method is nil but XcodeRunner.Run was just called")
	}
	callInfo := struct {
		Args []string
	}{
		Args: args,
	}
	mock.lockRun.Lock()
	mock.calls.Run = append(mock.calls.Run, callInfo)
	mock.lockRun.Unlock()
	return mock.RunFunc(args)
}

// RunCalls gets all the calls that were made to Run.
// Check the length with:
//
//	len(mockedXcodeRunner.RunCalls())
func (mock *XcodeRunnerMock) RunCalls() []struct {
	Args []string
} {
	var calls []struct {
		Args []string
	}
	mock.lockRun.RLock()
	calls = mock.calls.Run
	mock.lockRun.RUnlock()
	return calls
}
