// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package reactnative

import (
	"sync"
	"time"
)

// Ensure, that postRunRunnerMock does implement postRunRunner.
// If this is not the case, regenerate this file with moq.
var _ postRunRunner = &postRunRunnerMock{}

// postRunRunnerMock is a mock implementation of postRunRunner.
//
//	func TestSomethingThatUsespostRunRunner(t *testing.T) {
//
//		// make and configure a mocked postRunRunner
//		mockedpostRunRunner := &postRunRunnerMock{
//			runFunc: func(invocationID string, args []string, duration time.Duration, execErr error, ccacheInvocationID string)  {
//				panic("mock out the run method")
//			},
//		}
//
//		// use mockedpostRunRunner in code that requires postRunRunner
//		// and then make assertions.
//
//	}
type postRunRunnerMock struct {
	// runFunc mocks the run method.
	runFunc func(invocationID string, args []string, duration time.Duration, execErr error, ccacheInvocationID string)

	// calls tracks calls to the methods.
	calls struct {
		// run holds details about calls to the run method.
		run []struct {
			// InvocationID is the invocationID argument value.
			InvocationID string
			// Args is the args argument value.
			Args []string
			// Duration is the duration argument value.
			Duration time.Duration
			// ExecErr is the execErr argument value.
			ExecErr error
			// CcacheInvocationID is the ccacheInvocationID argument value.
			CcacheInvocationID string
		}
	}
	lockrun sync.RWMutex
}

// run calls runFunc.
func (mock *postRunRunnerMock) run(invocationID string, args []string, duration time.Duration, execErr error, ccacheInvocationID string) {
	callInfo := struct {
		InvocationID       string
		Args               []string
		Duration           time.Duration
		ExecErr            error
		CcacheInvocationID string
	}{
		InvocationID:       invocationID,
		Args:               args,
		Duration:           duration,
		ExecErr:            execErr,
		CcacheInvocationID: ccacheInvocationID,
	}
	mock.lockrun.Lock()
	mock.calls.run = append(mock.calls.run, callInfo)
	mock.lockrun.Unlock()
	if mock.runFunc == nil {
		return
	}
	mock.runFunc(invocationID, args, duration, execErr, ccacheInvocationID)
}

// runCalls gets all the calls that were made to run.
// Check the length with:
//
//	len(mockedpostRunRunner.runCalls())
func (mock *postRunRunnerMock) runCalls() []struct {
	InvocationID       string
	Args               []string
	Duration           time.Duration
	ExecErr            error
	CcacheInvocationID string
} {
	var calls []struct {
		InvocationID       string
		Args               []string
		Duration           time.Duration
		ExecErr            error
		CcacheInvocationID string
	}
	mock.lockrun.RLock()
	calls = mock.calls.run
	mock.lockrun.RUnlock()
	return calls
}
