// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package reactnative

import (
	"github.com/bitrise-io/bitrise-build-cache-cli/v3/internal/analytics/multiplatform"
	"sync"
)

// Ensure, that invocationClientMock does implement invocationClient.
// If this is not the case, regenerate this file with moq.
var _ invocationClient = &invocationClientMock{}

// invocationClientMock is a mock implementation of invocationClient.
//
//	func TestSomethingThatUsesinvocationClient(t *testing.T) {
//
//		// make and configure a mocked invocationClient
//		mockedinvocationClient := &invocationClientMock{
//			PutInvocationFunc: func(inv multiplatform.Invocation) error {
//				panic("mock out the PutInvocation method")
//			},
//		}
//
//		// use mockedinvocationClient in code that requires invocationClient
//		// and then make assertions.
//
//	}
type invocationClientMock struct {
	// PutInvocationFunc mocks the PutInvocation method.
	PutInvocationFunc func(inv multiplatform.Invocation) error

	// calls tracks calls to the methods.
	calls struct {
		// PutInvocation holds details about calls to the PutInvocation method.
		PutInvocation []struct {
			// Inv is the inv argument value.
			Inv multiplatform.Invocation
		}
	}
	lockPutInvocation sync.RWMutex
}

// PutInvocation calls PutInvocationFunc.
func (mock *invocationClientMock) PutInvocation(inv multiplatform.Invocation) error {
	callInfo := struct {
		Inv multiplatform.Invocation
	}{
		Inv: inv,
	}
	mock.lockPutInvocation.Lock()
	mock.calls.PutInvocation = append(mock.calls.PutInvocation, callInfo)
	mock.lockPutInvocation.Unlock()
	if mock.PutInvocationFunc == nil {
		var (
			errOut error
		)
		return errOut
	}
	return mock.PutInvocationFunc(inv)
}

// PutInvocationCalls gets all the calls that were made to PutInvocation.
// Check the length with:
//
//	len(mockedinvocationClient.PutInvocationCalls())
func (mock *invocationClientMock) PutInvocationCalls() []struct {
	Inv multiplatform.Invocation
} {
	var calls []struct {
		Inv multiplatform.Invocation
	}
	mock.lockPutInvocation.RLock()
	calls = mock.calls.PutInvocation
	mock.lockPutInvocation.RUnlock()
	return calls
}
