// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package reactnative

import (
	"context"
	"sync"
	"time"
)

// Ensure, that postRunRunnerMock does implement postRunRunner.
// If this is not the case, regenerate this file with moq.
var _ postRunRunner = &postRunRunnerMock{}

// postRunRunnerMock is a mock implementation of postRunRunner.
//
//	func TestSomethingThatUsespostRunRunner(t *testing.T) {
//
//		// make and configure a mocked postRunRunner
//		mockedpostRunRunner := &postRunRunnerMock{
//			runFunc: func(contextMoqParam context.Context, wrapperInvocationID string, args []string, duration time.Duration, execErr error)  {
//				panic("mock out the run method")
//			},
//		}
//
//		// use mockedpostRunRunner in code that requires postRunRunner
//		// and then make assertions.
//
//	}
type postRunRunnerMock struct {
	// runFunc mocks the run method.
	runFunc func(contextMoqParam context.Context, wrapperInvocationID string, args []string, duration time.Duration, execErr error)

	// calls tracks calls to the methods.
	calls struct {
		// run holds details about calls to the run method.
		run []struct {
			// ContextMoqParam is the contextMoqParam argument value.
			ContextMoqParam context.Context
			// WrapperInvocationID is the wrapperInvocationID argument value.
			WrapperInvocationID string
			// Args is the args argument value.
			Args []string
			// Duration is the duration argument value.
			Duration time.Duration
			// ExecErr is the execErr argument value.
			ExecErr error
		}
	}
	lockrun sync.RWMutex
}

// run calls runFunc.
func (mock *postRunRunnerMock) run(contextMoqParam context.Context, wrapperInvocationID string, args []string, duration time.Duration, execErr error) {
	callInfo := struct {
		ContextMoqParam     context.Context
		WrapperInvocationID string
		Args                []string
		Duration            time.Duration
		ExecErr             error
	}{
		ContextMoqParam:     contextMoqParam,
		WrapperInvocationID: wrapperInvocationID,
		Args:                args,
		Duration:            duration,
		ExecErr:             execErr,
	}
	mock.lockrun.Lock()
	mock.calls.run = append(mock.calls.run, callInfo)
	mock.lockrun.Unlock()
	if mock.runFunc == nil {
		return
	}
	mock.runFunc(contextMoqParam, wrapperInvocationID, args, duration, execErr)
}

// runCalls gets all the calls that were made to run.
// Check the length with:
//
//	len(mockedpostRunRunner.runCalls())
func (mock *postRunRunnerMock) runCalls() []struct {
	ContextMoqParam     context.Context
	WrapperInvocationID string
	Args                []string
	Duration            time.Duration
	ExecErr             error
} {
	var calls []struct {
		ContextMoqParam     context.Context
		WrapperInvocationID string
		Args                []string
		Duration            time.Duration
		ExecErr             error
	}
	mock.lockrun.RLock()
	calls = mock.calls.run
	mock.lockrun.RUnlock()
	return calls
}
