// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package reactnative

import (
	"context"
	"github.com/bitrise-io/bitrise-build-cache-cli/internal/analytics/multiplatform"
	configcommon "github.com/bitrise-io/bitrise-build-cache-cli/internal/config/common"
	"sync"
)

// Ensure, that postRunHookMock does implement postRunHook.
// If this is not the case, regenerate this file with moq.
var _ postRunHook = &postRunHookMock{}

// postRunHookMock is a mock implementation of postRunHook.
//
//	func TestSomethingThatUsespostRunHook(t *testing.T) {
//
//		// make and configure a mocked postRunHook
//		mockedpostRunHook := &postRunHookMock{
//			collectStatsFunc: func(ctx context.Context, ccacheInvocationID string, parentID string)  {
//				panic("mock out the collectStats method")
//			},
//			getAuthConfigFunc: func() (configcommon.CacheAuthConfig, error) {
//				panic("mock out the getAuthConfig method")
//			},
//			getMetadataFunc: func() configcommon.CacheConfigMetadata {
//				panic("mock out the getMetadata method")
//			},
//			sendInvocationFunc: func(inv multiplatform.Invocation) error {
//				panic("mock out the sendInvocation method")
//			},
//			sendRelationFunc: func(ctx context.Context, parentID string, childID string)  {
//				panic("mock out the sendRelation method")
//			},
//		}
//
//		// use mockedpostRunHook in code that requires postRunHook
//		// and then make assertions.
//
//	}
type postRunHookMock struct {
	// collectStatsFunc mocks the collectStats method.
	collectStatsFunc func(ctx context.Context, ccacheInvocationID string, parentID string)

	// getAuthConfigFunc mocks the getAuthConfig method.
	getAuthConfigFunc func() (configcommon.CacheAuthConfig, error)

	// getMetadataFunc mocks the getMetadata method.
	getMetadataFunc func() configcommon.CacheConfigMetadata

	// sendInvocationFunc mocks the sendInvocation method.
	sendInvocationFunc func(inv multiplatform.Invocation) error

	// sendRelationFunc mocks the sendRelation method.
	sendRelationFunc func(ctx context.Context, parentID string, childID string)

	// calls tracks calls to the methods.
	calls struct {
		// collectStats holds details about calls to the collectStats method.
		collectStats []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// CcacheInvocationID is the ccacheInvocationID argument value.
			CcacheInvocationID string
			// ParentID is the parentID argument value.
			ParentID string
		}
		// getAuthConfig holds details about calls to the getAuthConfig method.
		getAuthConfig []struct {
		}
		// getMetadata holds details about calls to the getMetadata method.
		getMetadata []struct {
		}
		// sendInvocation holds details about calls to the sendInvocation method.
		sendInvocation []struct {
			// Inv is the inv argument value.
			Inv multiplatform.Invocation
		}
		// sendRelation holds details about calls to the sendRelation method.
		sendRelation []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ParentID is the parentID argument value.
			ParentID string
			// ChildID is the childID argument value.
			ChildID string
		}
	}
	lockcollectStats   sync.RWMutex
	lockgetAuthConfig  sync.RWMutex
	lockgetMetadata    sync.RWMutex
	locksendInvocation sync.RWMutex
	locksendRelation   sync.RWMutex
}

// collectStats calls collectStatsFunc.
func (mock *postRunHookMock) collectStats(ctx context.Context, ccacheInvocationID string, parentID string) {
	callInfo := struct {
		Ctx                context.Context
		CcacheInvocationID string
		ParentID           string
	}{
		Ctx:                ctx,
		CcacheInvocationID: ccacheInvocationID,
		ParentID:           parentID,
	}
	mock.lockcollectStats.Lock()
	mock.calls.collectStats = append(mock.calls.collectStats, callInfo)
	mock.lockcollectStats.Unlock()
	if mock.collectStatsFunc == nil {
		return
	}
	mock.collectStatsFunc(ctx, ccacheInvocationID, parentID)
}

// collectStatsCalls gets all the calls that were made to collectStats.
// Check the length with:
//
//	len(mockedpostRunHook.collectStatsCalls())
func (mock *postRunHookMock) collectStatsCalls() []struct {
	Ctx                context.Context
	CcacheInvocationID string
	ParentID           string
} {
	var calls []struct {
		Ctx                context.Context
		CcacheInvocationID string
		ParentID           string
	}
	mock.lockcollectStats.RLock()
	calls = mock.calls.collectStats
	mock.lockcollectStats.RUnlock()
	return calls
}

// getAuthConfig calls getAuthConfigFunc.
func (mock *postRunHookMock) getAuthConfig() (configcommon.CacheAuthConfig, error) {
	callInfo := struct {
	}{}
	mock.lockgetAuthConfig.Lock()
	mock.calls.getAuthConfig = append(mock.calls.getAuthConfig, callInfo)
	mock.lockgetAuthConfig.Unlock()
	if mock.getAuthConfigFunc == nil {
		var (
			cacheAuthConfigOut configcommon.CacheAuthConfig
			errOut             error
		)
		return cacheAuthConfigOut, errOut
	}
	return mock.getAuthConfigFunc()
}

// getAuthConfigCalls gets all the calls that were made to getAuthConfig.
// Check the length with:
//
//	len(mockedpostRunHook.getAuthConfigCalls())
func (mock *postRunHookMock) getAuthConfigCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockgetAuthConfig.RLock()
	calls = mock.calls.getAuthConfig
	mock.lockgetAuthConfig.RUnlock()
	return calls
}

// getMetadata calls getMetadataFunc.
func (mock *postRunHookMock) getMetadata() configcommon.CacheConfigMetadata {
	callInfo := struct {
	}{}
	mock.lockgetMetadata.Lock()
	mock.calls.getMetadata = append(mock.calls.getMetadata, callInfo)
	mock.lockgetMetadata.Unlock()
	if mock.getMetadataFunc == nil {
		var (
			cacheConfigMetadataOut configcommon.CacheConfigMetadata
		)
		return cacheConfigMetadataOut
	}
	return mock.getMetadataFunc()
}

// getMetadataCalls gets all the calls that were made to getMetadata.
// Check the length with:
//
//	len(mockedpostRunHook.getMetadataCalls())
func (mock *postRunHookMock) getMetadataCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockgetMetadata.RLock()
	calls = mock.calls.getMetadata
	mock.lockgetMetadata.RUnlock()
	return calls
}

// sendInvocation calls sendInvocationFunc.
func (mock *postRunHookMock) sendInvocation(inv multiplatform.Invocation) error {
	callInfo := struct {
		Inv multiplatform.Invocation
	}{
		Inv: inv,
	}
	mock.locksendInvocation.Lock()
	mock.calls.sendInvocation = append(mock.calls.sendInvocation, callInfo)
	mock.locksendInvocation.Unlock()
	if mock.sendInvocationFunc == nil {
		var (
			errOut error
		)
		return errOut
	}
	return mock.sendInvocationFunc(inv)
}

// sendInvocationCalls gets all the calls that were made to sendInvocation.
// Check the length with:
//
//	len(mockedpostRunHook.sendInvocationCalls())
func (mock *postRunHookMock) sendInvocationCalls() []struct {
	Inv multiplatform.Invocation
} {
	var calls []struct {
		Inv multiplatform.Invocation
	}
	mock.locksendInvocation.RLock()
	calls = mock.calls.sendInvocation
	mock.locksendInvocation.RUnlock()
	return calls
}

// sendRelation calls sendRelationFunc.
func (mock *postRunHookMock) sendRelation(ctx context.Context, parentID string, childID string) {
	callInfo := struct {
		Ctx      context.Context
		ParentID string
		ChildID  string
	}{
		Ctx:      ctx,
		ParentID: parentID,
		ChildID:  childID,
	}
	mock.locksendRelation.Lock()
	mock.calls.sendRelation = append(mock.calls.sendRelation, callInfo)
	mock.locksendRelation.Unlock()
	if mock.sendRelationFunc == nil {
		return
	}
	mock.sendRelationFunc(ctx, parentID, childID)
}

// sendRelationCalls gets all the calls that were made to sendRelation.
// Check the length with:
//
//	len(mockedpostRunHook.sendRelationCalls())
func (mock *postRunHookMock) sendRelationCalls() []struct {
	Ctx      context.Context
	ParentID string
	ChildID  string
} {
	var calls []struct {
		Ctx      context.Context
		ParentID string
		ChildID  string
	}
	mock.locksendRelation.RLock()
	calls = mock.calls.sendRelation
	mock.locksendRelation.RUnlock()
	return calls
}
