linters:
  enable-all: true
  disable:
  - funlen
  - gochecknoinits
  - lll # line too long
  - godot # "comment should end in a period"
  - gofumpt
  - wsl
  - depguard
  - exhaustruct
  - paralleltest
  - testpackage
  - mnd
  - err113
  - perfsprint
  - varnamelen
  - gci
  - nolintlint
  - cyclop
