linters:
  enable-all: true
  disable:
  - varcheck # deprecated
  - deadcode # deprecated
  - interfacer # deprecated
  - golint # deprecated
  - nosnakecase # deprecated
  - structcheck # deprecated
  - exhaustivestruct # deprecated
  - ifshort # deprecated
  - maligned # deprecated
  - scopelint # deprecated
  - funlen
  - gochecknoinits
  - lll # line too long
  - godot # "comment should end in a period"
  - gofumpt
  - wsl
  - depguard
  - exhaustruct
  - paralleltest
  - testpackage
  - mnd
  - gomnd
  - err113 # ensble use of dynamic errors fmt.Errorf("error: %s", str)
