version: "2"
linters:
  default: all
  disable:
    - cyclop
    - depguard
    - err113
    - exhaustruct
    - funcorder
    - funlen
    - gochecknoinits
    - godot
    - godox
    - ireturn
    - lll
    - mnd
    - noinlineerr
    - nolintlint
    - paralleltest
    - perfsprint
    - revive
    - tagliatelle
    - testpackage
    - varnamelen
    - wsl
    - wsl_v5
    - ireturn
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - third_party$
      - builtin$
      - examples$
      - proto/*
      - mocks/*
formatters:
  enable:
    - gofmt
    - goimports
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
