# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
# vim: set ts=2 sw=2 tw=0 fo=cnqoj

version: 1

project_name: bitrise-build-cache

# Based on https://goreleaser.com/customization/release/#github
release:
  github:
    owner: bitrise-io
    name: bitrise-build-cache-cli
  make_latest: true
  draft: false
  mode: append
  replace_existing_artifacts: true
  footer: |
    ### Gradle verification
    For reference, the verification metadata is available as an attached assset.
  extra_files:
    - glob: ./cmd/gradle/asset/verification-metadata.xml


before:
  hooks:
    - go mod tidy

builds:
  - binary: bitrise-build-cache
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      # - windows
      - darwin

archives:
  - name_template: 'bitrise-build-cache_{{ .Version }}_{{ .Os }}_{{ .Arch }}'

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
