// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package mocks

import (
	"github.com/bitrise-io/bitrise-build-cache-cli/v3/internal/xcelerate/xcodeargs"
	"sync"
)

// Ensure, that XcodeArgsMock does implement xcodeargs.XcodeArgs.
// If this is not the case, regenerate this file with moq.
var _ xcodeargs.XcodeArgs = &XcodeArgsMock{}

// XcodeArgsMock is a mock implementation of xcodeargs.XcodeArgs.
//
//	func TestSomethingThatUsesXcodeArgs(t *testing.T) {
//
//		// make and configure a mocked xcodeargs.XcodeArgs
//		mockedXcodeArgs := &XcodeArgsMock{
//			ArgsFunc: func(additional map[string]string) []string {
//				panic("mock out the Args method")
//			},
//			CommandFunc: func() string {
//				panic("mock out the Command method")
//			},
//			DerivedDataPathFunc: func() string {
//				panic("mock out the DerivedDataPath method")
//			},
//			HasBuildActionFunc: func() bool {
//				panic("mock out the HasBuildAction method")
//			},
//			ProjectDirFunc: func() string {
//				panic("mock out the ProjectDir method")
//			},
//			ProjectTempDirFunc: func() string {
//				panic("mock out the ProjectTempDir method")
//			},
//			ShortCommandFunc: func() string {
//				panic("mock out the ShortCommand method")
//			},
//			UserOtherCFlagsFunc: func() string {
//				panic("mock out the UserOtherCFlags method")
//			},
//		}
//
//		// use mockedXcodeArgs in code that requires xcodeargs.XcodeArgs
//		// and then make assertions.
//
//	}
type XcodeArgsMock struct {
	// ArgsFunc mocks the Args method.
	ArgsFunc func(additional map[string]string) []string

	// CommandFunc mocks the Command method.
	CommandFunc func() string

	// DerivedDataPathFunc mocks the DerivedDataPath method.
	DerivedDataPathFunc func() string

	// HasBuildActionFunc mocks the HasBuildAction method.
	HasBuildActionFunc func() bool

	// ProjectDirFunc mocks the ProjectDir method.
	ProjectDirFunc func() string

	// ProjectTempDirFunc mocks the ProjectTempDir method.
	ProjectTempDirFunc func() string

	// ShortCommandFunc mocks the ShortCommand method.
	ShortCommandFunc func() string

	// UserOtherCFlagsFunc mocks the UserOtherCFlags method.
	UserOtherCFlagsFunc func() string

	// calls tracks calls to the methods.
	calls struct {
		// Args holds details about calls to the Args method.
		Args []struct {
			// Additional is the additional argument value.
			Additional map[string]string
		}
		// Command holds details about calls to the Command method.
		Command []struct {
		}
		// DerivedDataPath holds details about calls to the DerivedDataPath method.
		DerivedDataPath []struct {
		}
		// HasBuildAction holds details about calls to the HasBuildAction method.
		HasBuildAction []struct {
		}
		// ProjectDir holds details about calls to the ProjectDir method.
		ProjectDir []struct {
		}
		// ProjectTempDir holds details about calls to the ProjectTempDir method.
		ProjectTempDir []struct {
		}
		// ShortCommand holds details about calls to the ShortCommand method.
		ShortCommand []struct {
		}
		// UserOtherCFlags holds details about calls to the UserOtherCFlags method.
		UserOtherCFlags []struct {
		}
	}
	lockArgs            sync.RWMutex
	lockCommand         sync.RWMutex
	lockDerivedDataPath sync.RWMutex
	lockHasBuildAction  sync.RWMutex
	lockProjectDir      sync.RWMutex
	lockProjectTempDir  sync.RWMutex
	lockShortCommand    sync.RWMutex
	lockUserOtherCFlags sync.RWMutex
}

// Args calls ArgsFunc.
func (mock *XcodeArgsMock) Args(additional map[string]string) []string {
	callInfo := struct {
		Additional map[string]string
	}{
		Additional: additional,
	}
	mock.lockArgs.Lock()
	mock.calls.Args = append(mock.calls.Args, callInfo)
	mock.lockArgs.Unlock()
	if mock.ArgsFunc == nil {
		var (
			stringsOut []string
		)
		return stringsOut
	}
	return mock.ArgsFunc(additional)
}

// ArgsCalls gets all the calls that were made to Args.
// Check the length with:
//
//	len(mockedXcodeArgs.ArgsCalls())
func (mock *XcodeArgsMock) ArgsCalls() []struct {
	Additional map[string]string
} {
	var calls []struct {
		Additional map[string]string
	}
	mock.lockArgs.RLock()
	calls = mock.calls.Args
	mock.lockArgs.RUnlock()
	return calls
}

// Command calls CommandFunc.
func (mock *XcodeArgsMock) Command() string {
	callInfo := struct {
	}{}
	mock.lockCommand.Lock()
	mock.calls.Command = append(mock.calls.Command, callInfo)
	mock.lockCommand.Unlock()
	if mock.CommandFunc == nil {
		var (
			sOut string
		)
		return sOut
	}
	return mock.CommandFunc()
}

// CommandCalls gets all the calls that were made to Command.
// Check the length with:
//
//	len(mockedXcodeArgs.CommandCalls())
func (mock *XcodeArgsMock) CommandCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockCommand.RLock()
	calls = mock.calls.Command
	mock.lockCommand.RUnlock()
	return calls
}

// DerivedDataPath calls DerivedDataPathFunc.
func (mock *XcodeArgsMock) DerivedDataPath() string {
	callInfo := struct {
	}{}
	mock.lockDerivedDataPath.Lock()
	mock.calls.DerivedDataPath = append(mock.calls.DerivedDataPath, callInfo)
	mock.lockDerivedDataPath.Unlock()
	if mock.DerivedDataPathFunc == nil {
		var (
			sOut string
		)
		return sOut
	}
	return mock.DerivedDataPathFunc()
}

// DerivedDataPathCalls gets all the calls that were made to DerivedDataPath.
// Check the length with:
//
//	len(mockedXcodeArgs.DerivedDataPathCalls())
func (mock *XcodeArgsMock) DerivedDataPathCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockDerivedDataPath.RLock()
	calls = mock.calls.DerivedDataPath
	mock.lockDerivedDataPath.RUnlock()
	return calls
}

// HasBuildAction calls HasBuildActionFunc.
func (mock *XcodeArgsMock) HasBuildAction() bool {
	callInfo := struct {
	}{}
	mock.lockHasBuildAction.Lock()
	mock.calls.HasBuildAction = append(mock.calls.HasBuildAction, callInfo)
	mock.lockHasBuildAction.Unlock()
	if mock.HasBuildActionFunc == nil {
		var (
			bOut bool
		)
		return bOut
	}
	return mock.HasBuildActionFunc()
}

// HasBuildActionCalls gets all the calls that were made to HasBuildAction.
// Check the length with:
//
//	len(mockedXcodeArgs.HasBuildActionCalls())
func (mock *XcodeArgsMock) HasBuildActionCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockHasBuildAction.RLock()
	calls = mock.calls.HasBuildAction
	mock.lockHasBuildAction.RUnlock()
	return calls
}

// ProjectDir calls ProjectDirFunc.
func (mock *XcodeArgsMock) ProjectDir() string {
	callInfo := struct {
	}{}
	mock.lockProjectDir.Lock()
	mock.calls.ProjectDir = append(mock.calls.ProjectDir, callInfo)
	mock.lockProjectDir.Unlock()
	if mock.ProjectDirFunc == nil {
		var (
			sOut string
		)
		return sOut
	}
	return mock.ProjectDirFunc()
}

// ProjectDirCalls gets all the calls that were made to ProjectDir.
// Check the length with:
//
//	len(mockedXcodeArgs.ProjectDirCalls())
func (mock *XcodeArgsMock) ProjectDirCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockProjectDir.RLock()
	calls = mock.calls.ProjectDir
	mock.lockProjectDir.RUnlock()
	return calls
}

// ProjectTempDir calls ProjectTempDirFunc.
func (mock *XcodeArgsMock) ProjectTempDir() string {
	callInfo := struct {
	}{}
	mock.lockProjectTempDir.Lock()
	mock.calls.ProjectTempDir = append(mock.calls.ProjectTempDir, callInfo)
	mock.lockProjectTempDir.Unlock()
	if mock.ProjectTempDirFunc == nil {
		var (
			sOut string
		)
		return sOut
	}
	return mock.ProjectTempDirFunc()
}

// ProjectTempDirCalls gets all the calls that were made to ProjectTempDir.
// Check the length with:
//
//	len(mockedXcodeArgs.ProjectTempDirCalls())
func (mock *XcodeArgsMock) ProjectTempDirCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockProjectTempDir.RLock()
	calls = mock.calls.ProjectTempDir
	mock.lockProjectTempDir.RUnlock()
	return calls
}

// ShortCommand calls ShortCommandFunc.
func (mock *XcodeArgsMock) ShortCommand() string {
	callInfo := struct {
	}{}
	mock.lockShortCommand.Lock()
	mock.calls.ShortCommand = append(mock.calls.ShortCommand, callInfo)
	mock.lockShortCommand.Unlock()
	if mock.ShortCommandFunc == nil {
		var (
			sOut string
		)
		return sOut
	}
	return mock.ShortCommandFunc()
}

// ShortCommandCalls gets all the calls that were made to ShortCommand.
// Check the length with:
//
//	len(mockedXcodeArgs.ShortCommandCalls())
func (mock *XcodeArgsMock) ShortCommandCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockShortCommand.RLock()
	calls = mock.calls.ShortCommand
	mock.lockShortCommand.RUnlock()
	return calls
}

// UserOtherCFlags calls UserOtherCFlagsFunc.
func (mock *XcodeArgsMock) UserOtherCFlags() string {
	callInfo := struct {
	}{}
	mock.lockUserOtherCFlags.Lock()
	mock.calls.UserOtherCFlags = append(mock.calls.UserOtherCFlags, callInfo)
	mock.lockUserOtherCFlags.Unlock()
	if mock.UserOtherCFlagsFunc == nil {
		var (
			sOut string
		)
		return sOut
	}
	return mock.UserOtherCFlagsFunc()
}

// UserOtherCFlagsCalls gets all the calls that were made to UserOtherCFlags.
// Check the length with:
//
//	len(mockedXcodeArgs.UserOtherCFlagsCalls())
func (mock *XcodeArgsMock) UserOtherCFlagsCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockUserOtherCFlags.RLock()
	calls = mock.calls.UserOtherCFlags
	mock.lockUserOtherCFlags.RUnlock()
	return calls
}
