// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package mocks

import (
	"github.com/bitrise-io/bitrise-build-cache-cli/internal/utils"
	"io"
	"sync"
)

// Ensure, that EncoderFactoryMock does implement utils.EncoderFactory.
// If this is not the case, regenerate this file with moq.
var _ utils.EncoderFactory = &EncoderFactoryMock{}

// EncoderFactoryMock is a mock implementation of utils.EncoderFactory.
//
//	func TestSomethingThatUsesEncoderFactory(t *testing.T) {
//
//		// make and configure a mocked utils.EncoderFactory
//		mockedEncoderFactory := &EncoderFactoryMock{
//			EncoderFunc: func(w io.Writer) utils.Encoder {
//				panic("mock out the Encoder method")
//			},
//		}
//
//		// use mockedEncoderFactory in code that requires utils.EncoderFactory
//		// and then make assertions.
//
//	}
type EncoderFactoryMock struct {
	// EncoderFunc mocks the Encoder method.
	EncoderFunc func(w io.Writer) utils.Encoder

	// calls tracks calls to the methods.
	calls struct {
		// Encoder holds details about calls to the Encoder method.
		Encoder []struct {
			// W is the w argument value.
			W io.Writer
		}
	}
	lockEncoder sync.RWMutex
}

// Encoder calls EncoderFunc.
func (mock *EncoderFactoryMock) Encoder(w io.Writer) utils.Encoder {
	if mock.EncoderFunc == nil {
		panic("EncoderFactoryMock.EncoderFunc: method is nil but EncoderFactory.Encoder was just called")
	}
	callInfo := struct {
		W io.Writer
	}{
		W: w,
	}
	mock.lockEncoder.Lock()
	mock.calls.Encoder = append(mock.calls.Encoder, callInfo)
	mock.lockEncoder.Unlock()
	return mock.EncoderFunc(w)
}

// EncoderCalls gets all the calls that were made to Encoder.
// Check the length with:
//
//	len(mockedEncoderFactory.EncoderCalls())
func (mock *EncoderFactoryMock) EncoderCalls() []struct {
	W io.Writer
} {
	var calls []struct {
		W io.Writer
	}
	mock.lockEncoder.RLock()
	calls = mock.calls.Encoder
	mock.lockEncoder.RUnlock()
	return calls
}
