// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package invoke_test

import (
	"context"
	"github.com/bitrise-io/bitrise-build-cache-cli/v3/pkg/xcode/invoke"
	"sync"
)

// Ensure, that PromptMock does implement invoke.Prompt.
// If this is not the case, regenerate this file with moq.
var _ invoke.Prompt = &PromptMock{}

// PromptMock is a mock implementation of invoke.Prompt.
//
//	func TestSomethingThatUsesPrompt(t *testing.T) {
//
//		// make and configure a mocked invoke.Prompt
//		mockedPrompt := &PromptMock{
//			FillFunc: func(ctx context.Context, spec *invoke.InvocationSpec) error {
//				panic("mock out the Fill method")
//			},
//		}
//
//		// use mockedPrompt in code that requires invoke.Prompt
//		// and then make assertions.
//
//	}
type PromptMock struct {
	// FillFunc mocks the Fill method.
	FillFunc func(ctx context.Context, spec *invoke.InvocationSpec) error

	// calls tracks calls to the methods.
	calls struct {
		// Fill holds details about calls to the Fill method.
		Fill []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Spec is the spec argument value.
			Spec *invoke.InvocationSpec
		}
	}
	lockFill sync.RWMutex
}

// Fill calls FillFunc.
func (mock *PromptMock) Fill(ctx context.Context, spec *invoke.InvocationSpec) error {
	callInfo := struct {
		Ctx  context.Context
		Spec *invoke.InvocationSpec
	}{
		Ctx:  ctx,
		Spec: spec,
	}
	mock.lockFill.Lock()
	mock.calls.Fill = append(mock.calls.Fill, callInfo)
	mock.lockFill.Unlock()
	if mock.FillFunc == nil {
		var (
			errOut error
		)
		return errOut
	}
	return mock.FillFunc(ctx, spec)
}

// FillCalls gets all the calls that were made to Fill.
// Check the length with:
//
//	len(mockedPrompt.FillCalls())
func (mock *PromptMock) FillCalls() []struct {
	Ctx  context.Context
	Spec *invoke.InvocationSpec
} {
	var calls []struct {
		Ctx  context.Context
		Spec *invoke.InvocationSpec
	}
	mock.lockFill.RLock()
	calls = mock.calls.Fill
	mock.lockFill.RUnlock()
	return calls
}
