// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package invoke

import (
	"context"
	"sync"
)

// Ensure, that xcodebuildInfoProviderMock does implement xcodebuildInfoProvider.
// If this is not the case, regenerate this file with moq.
var _ xcodebuildInfoProvider = &xcodebuildInfoProviderMock{}

// xcodebuildInfoProviderMock is a mock implementation of xcodebuildInfoProvider.
//
//	func TestSomethingThatUsesxcodebuildInfoProvider(t *testing.T) {
//
//		// make and configure a mocked xcodebuildInfoProvider
//		mockedxcodebuildInfoProvider := &xcodebuildInfoProviderMock{
//			ListSchemesAndConfigurationsFunc: func(ctx context.Context, workspace string, project string) ([]string, []string, error) {
//				panic("mock out the ListSchemesAndConfigurations method")
//			},
//			ShowDestinationsFunc: func(ctx context.Context, workspace string, project string, scheme string) ([]string, error) {
//				panic("mock out the ShowDestinations method")
//			},
//		}
//
//		// use mockedxcodebuildInfoProvider in code that requires xcodebuildInfoProvider
//		// and then make assertions.
//
//	}
type xcodebuildInfoProviderMock struct {
	// ListSchemesAndConfigurationsFunc mocks the ListSchemesAndConfigurations method.
	ListSchemesAndConfigurationsFunc func(ctx context.Context, workspace string, project string) ([]string, []string, error)

	// ShowDestinationsFunc mocks the ShowDestinations method.
	ShowDestinationsFunc func(ctx context.Context, workspace string, project string, scheme string) ([]string, error)

	// calls tracks calls to the methods.
	calls struct {
		// ListSchemesAndConfigurations holds details about calls to the ListSchemesAndConfigurations method.
		ListSchemesAndConfigurations []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Workspace is the workspace argument value.
			Workspace string
			// Project is the project argument value.
			Project string
		}
		// ShowDestinations holds details about calls to the ShowDestinations method.
		ShowDestinations []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Workspace is the workspace argument value.
			Workspace string
			// Project is the project argument value.
			Project string
			// Scheme is the scheme argument value.
			Scheme string
		}
	}
	lockListSchemesAndConfigurations sync.RWMutex
	lockShowDestinations             sync.RWMutex
}

// ListSchemesAndConfigurations calls ListSchemesAndConfigurationsFunc.
func (mock *xcodebuildInfoProviderMock) ListSchemesAndConfigurations(ctx context.Context, workspace string, project string) ([]string, []string, error) {
	callInfo := struct {
		Ctx       context.Context
		Workspace string
		Project   string
	}{
		Ctx:       ctx,
		Workspace: workspace,
		Project:   project,
	}
	mock.lockListSchemesAndConfigurations.Lock()
	mock.calls.ListSchemesAndConfigurations = append(mock.calls.ListSchemesAndConfigurations, callInfo)
	mock.lockListSchemesAndConfigurations.Unlock()
	if mock.ListSchemesAndConfigurationsFunc == nil {
		var (
			schemesOut        []string
			configurationsOut []string
			errOut            error
		)
		return schemesOut, configurationsOut, errOut
	}
	return mock.ListSchemesAndConfigurationsFunc(ctx, workspace, project)
}

// ListSchemesAndConfigurationsCalls gets all the calls that were made to ListSchemesAndConfigurations.
// Check the length with:
//
//	len(mockedxcodebuildInfoProvider.ListSchemesAndConfigurationsCalls())
func (mock *xcodebuildInfoProviderMock) ListSchemesAndConfigurationsCalls() []struct {
	Ctx       context.Context
	Workspace string
	Project   string
} {
	var calls []struct {
		Ctx       context.Context
		Workspace string
		Project   string
	}
	mock.lockListSchemesAndConfigurations.RLock()
	calls = mock.calls.ListSchemesAndConfigurations
	mock.lockListSchemesAndConfigurations.RUnlock()
	return calls
}

// ShowDestinations calls ShowDestinationsFunc.
func (mock *xcodebuildInfoProviderMock) ShowDestinations(ctx context.Context, workspace string, project string, scheme string) ([]string, error) {
	callInfo := struct {
		Ctx       context.Context
		Workspace string
		Project   string
		Scheme    string
	}{
		Ctx:       ctx,
		Workspace: workspace,
		Project:   project,
		Scheme:    scheme,
	}
	mock.lockShowDestinations.Lock()
	mock.calls.ShowDestinations = append(mock.calls.ShowDestinations, callInfo)
	mock.lockShowDestinations.Unlock()
	if mock.ShowDestinationsFunc == nil {
		var (
			stringsOut []string
			errOut     error
		)
		return stringsOut, errOut
	}
	return mock.ShowDestinationsFunc(ctx, workspace, project, scheme)
}

// ShowDestinationsCalls gets all the calls that were made to ShowDestinations.
// Check the length with:
//
//	len(mockedxcodebuildInfoProvider.ShowDestinationsCalls())
func (mock *xcodebuildInfoProviderMock) ShowDestinationsCalls() []struct {
	Ctx       context.Context
	Workspace string
	Project   string
	Scheme    string
} {
	var calls []struct {
		Ctx       context.Context
		Workspace string
		Project   string
		Scheme    string
	}
	mock.lockShowDestinations.RLock()
	calls = mock.calls.ShowDestinations
	mock.lockShowDestinations.RUnlock()
	return calls
}
