// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package invoke

import (
	"context"
	"sync"
)

// Ensure, that xcodebuildInfoProviderMock does implement xcodebuildInfoProvider.
// If this is not the case, regenerate this file with moq.
var _ xcodebuildInfoProvider = &xcodebuildInfoProviderMock{}

// xcodebuildInfoProviderMock is a mock implementation of xcodebuildInfoProvider.
//
//	func TestSomethingThatUsesxcodebuildInfoProvider(t *testing.T) {
//
//		// make and configure a mocked xcodebuildInfoProvider
//		mockedxcodebuildInfoProvider := &xcodebuildInfoProviderMock{
//			ListConfigurationsFunc: func(ctx context.Context, workspace string, project string) ([]string, error) {
//				panic("mock out the ListConfigurations method")
//			},
//			ListSchemesFunc: func(ctx context.Context, workspace string, project string) ([]string, error) {
//				panic("mock out the ListSchemes method")
//			},
//			ShowDestinationsFunc: func(ctx context.Context, workspace string, project string, scheme string) ([]string, error) {
//				panic("mock out the ShowDestinations method")
//			},
//		}
//
//		// use mockedxcodebuildInfoProvider in code that requires xcodebuildInfoProvider
//		// and then make assertions.
//
//	}
type xcodebuildInfoProviderMock struct {
	// ListConfigurationsFunc mocks the ListConfigurations method.
	ListConfigurationsFunc func(ctx context.Context, workspace string, project string) ([]string, error)

	// ListSchemesFunc mocks the ListSchemes method.
	ListSchemesFunc func(ctx context.Context, workspace string, project string) ([]string, error)

	// ShowDestinationsFunc mocks the ShowDestinations method.
	ShowDestinationsFunc func(ctx context.Context, workspace string, project string, scheme string) ([]string, error)

	// calls tracks calls to the methods.
	calls struct {
		// ListConfigurations holds details about calls to the ListConfigurations method.
		ListConfigurations []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Workspace is the workspace argument value.
			Workspace string
			// Project is the project argument value.
			Project string
		}
		// ListSchemes holds details about calls to the ListSchemes method.
		ListSchemes []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Workspace is the workspace argument value.
			Workspace string
			// Project is the project argument value.
			Project string
		}
		// ShowDestinations holds details about calls to the ShowDestinations method.
		ShowDestinations []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Workspace is the workspace argument value.
			Workspace string
			// Project is the project argument value.
			Project string
			// Scheme is the scheme argument value.
			Scheme string
		}
	}
	lockListConfigurations sync.RWMutex
	lockListSchemes        sync.RWMutex
	lockShowDestinations   sync.RWMutex
}

// ListConfigurations calls ListConfigurationsFunc.
func (mock *xcodebuildInfoProviderMock) ListConfigurations(ctx context.Context, workspace string, project string) ([]string, error) {
	callInfo := struct {
		Ctx       context.Context
		Workspace string
		Project   string
	}{
		Ctx:       ctx,
		Workspace: workspace,
		Project:   project,
	}
	mock.lockListConfigurations.Lock()
	mock.calls.ListConfigurations = append(mock.calls.ListConfigurations, callInfo)
	mock.lockListConfigurations.Unlock()
	if mock.ListConfigurationsFunc == nil {
		var (
			stringsOut []string
			errOut     error
		)
		return stringsOut, errOut
	}
	return mock.ListConfigurationsFunc(ctx, workspace, project)
}

// ListConfigurationsCalls gets all the calls that were made to ListConfigurations.
// Check the length with:
//
//	len(mockedxcodebuildInfoProvider.ListConfigurationsCalls())
func (mock *xcodebuildInfoProviderMock) ListConfigurationsCalls() []struct {
	Ctx       context.Context
	Workspace string
	Project   string
} {
	var calls []struct {
		Ctx       context.Context
		Workspace string
		Project   string
	}
	mock.lockListConfigurations.RLock()
	calls = mock.calls.ListConfigurations
	mock.lockListConfigurations.RUnlock()
	return calls
}

// ListSchemes calls ListSchemesFunc.
func (mock *xcodebuildInfoProviderMock) ListSchemes(ctx context.Context, workspace string, project string) ([]string, error) {
	callInfo := struct {
		Ctx       context.Context
		Workspace string
		Project   string
	}{
		Ctx:       ctx,
		Workspace: workspace,
		Project:   project,
	}
	mock.lockListSchemes.Lock()
	mock.calls.ListSchemes = append(mock.calls.ListSchemes, callInfo)
	mock.lockListSchemes.Unlock()
	if mock.ListSchemesFunc == nil {
		var (
			stringsOut []string
			errOut     error
		)
		return stringsOut, errOut
	}
	return mock.ListSchemesFunc(ctx, workspace, project)
}

// ListSchemesCalls gets all the calls that were made to ListSchemes.
// Check the length with:
//
//	len(mockedxcodebuildInfoProvider.ListSchemesCalls())
func (mock *xcodebuildInfoProviderMock) ListSchemesCalls() []struct {
	Ctx       context.Context
	Workspace string
	Project   string
} {
	var calls []struct {
		Ctx       context.Context
		Workspace string
		Project   string
	}
	mock.lockListSchemes.RLock()
	calls = mock.calls.ListSchemes
	mock.lockListSchemes.RUnlock()
	return calls
}

// ShowDestinations calls ShowDestinationsFunc.
func (mock *xcodebuildInfoProviderMock) ShowDestinations(ctx context.Context, workspace string, project string, scheme string) ([]string, error) {
	callInfo := struct {
		Ctx       context.Context
		Workspace string
		Project   string
		Scheme    string
	}{
		Ctx:       ctx,
		Workspace: workspace,
		Project:   project,
		Scheme:    scheme,
	}
	mock.lockShowDestinations.Lock()
	mock.calls.ShowDestinations = append(mock.calls.ShowDestinations, callInfo)
	mock.lockShowDestinations.Unlock()
	if mock.ShowDestinationsFunc == nil {
		var (
			stringsOut []string
			errOut     error
		)
		return stringsOut, errOut
	}
	return mock.ShowDestinationsFunc(ctx, workspace, project, scheme)
}

// ShowDestinationsCalls gets all the calls that were made to ShowDestinations.
// Check the length with:
//
//	len(mockedxcodebuildInfoProvider.ShowDestinationsCalls())
func (mock *xcodebuildInfoProviderMock) ShowDestinationsCalls() []struct {
	Ctx       context.Context
	Workspace string
	Project   string
	Scheme    string
} {
	var calls []struct {
		Ctx       context.Context
		Workspace string
		Project   string
		Scheme    string
	}
	mock.lockShowDestinations.RLock()
	calls = mock.calls.ShowDestinations
	mock.lockShowDestinations.RUnlock()
	return calls
}
