// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package xcode

import (
	"context"
	"sync"
)

// Ensure, that buildHealthReporterMock does implement buildHealthReporter.
// If this is not the case, regenerate this file with moq.
var _ buildHealthReporter = &buildHealthReporterMock{}

// buildHealthReporterMock is a mock implementation of buildHealthReporter.
//
//	func TestSomethingThatUsesbuildHealthReporter(t *testing.T) {
//
//		// make and configure a mocked buildHealthReporter
//		mockedbuildHealthReporter := &buildHealthReporterMock{
//			CheckAtStartFunc: func(ctx context.Context)  {
//				panic("mock out the CheckAtStart method")
//			},
//			OnInvocationSaveFailureFunc: func(ctx context.Context)  {
//				panic("mock out the OnInvocationSaveFailure method")
//			},
//			ReportAtEndFunc: func(ctx context.Context, outcome buildOutcome)  {
//				panic("mock out the ReportAtEnd method")
//			},
//		}
//
//		// use mockedbuildHealthReporter in code that requires buildHealthReporter
//		// and then make assertions.
//
//	}
type buildHealthReporterMock struct {
	// CheckAtStartFunc mocks the CheckAtStart method.
	CheckAtStartFunc func(ctx context.Context)

	// OnInvocationSaveFailureFunc mocks the OnInvocationSaveFailure method.
	OnInvocationSaveFailureFunc func(ctx context.Context)

	// ReportAtEndFunc mocks the ReportAtEnd method.
	ReportAtEndFunc func(ctx context.Context, outcome buildOutcome)

	// calls tracks calls to the methods.
	calls struct {
		// CheckAtStart holds details about calls to the CheckAtStart method.
		CheckAtStart []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
		}
		// OnInvocationSaveFailure holds details about calls to the OnInvocationSaveFailure method.
		OnInvocationSaveFailure []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
		}
		// ReportAtEnd holds details about calls to the ReportAtEnd method.
		ReportAtEnd []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Outcome is the outcome argument value.
			Outcome buildOutcome
		}
	}
	lockCheckAtStart            sync.RWMutex
	lockOnInvocationSaveFailure sync.RWMutex
	lockReportAtEnd             sync.RWMutex
}

// CheckAtStart calls CheckAtStartFunc.
func (mock *buildHealthReporterMock) CheckAtStart(ctx context.Context) {
	callInfo := struct {
		Ctx context.Context
	}{
		Ctx: ctx,
	}
	mock.lockCheckAtStart.Lock()
	mock.calls.CheckAtStart = append(mock.calls.CheckAtStart, callInfo)
	mock.lockCheckAtStart.Unlock()
	if mock.CheckAtStartFunc == nil {
		return
	}
	mock.CheckAtStartFunc(ctx)
}

// CheckAtStartCalls gets all the calls that were made to CheckAtStart.
// Check the length with:
//
//	len(mockedbuildHealthReporter.CheckAtStartCalls())
func (mock *buildHealthReporterMock) CheckAtStartCalls() []struct {
	Ctx context.Context
} {
	var calls []struct {
		Ctx context.Context
	}
	mock.lockCheckAtStart.RLock()
	calls = mock.calls.CheckAtStart
	mock.lockCheckAtStart.RUnlock()
	return calls
}

// OnInvocationSaveFailure calls OnInvocationSaveFailureFunc.
func (mock *buildHealthReporterMock) OnInvocationSaveFailure(ctx context.Context) {
	callInfo := struct {
		Ctx context.Context
	}{
		Ctx: ctx,
	}
	mock.lockOnInvocationSaveFailure.Lock()
	mock.calls.OnInvocationSaveFailure = append(mock.calls.OnInvocationSaveFailure, callInfo)
	mock.lockOnInvocationSaveFailure.Unlock()
	if mock.OnInvocationSaveFailureFunc == nil {
		return
	}
	mock.OnInvocationSaveFailureFunc(ctx)
}

// OnInvocationSaveFailureCalls gets all the calls that were made to OnInvocationSaveFailure.
// Check the length with:
//
//	len(mockedbuildHealthReporter.OnInvocationSaveFailureCalls())
func (mock *buildHealthReporterMock) OnInvocationSaveFailureCalls() []struct {
	Ctx context.Context
} {
	var calls []struct {
		Ctx context.Context
	}
	mock.lockOnInvocationSaveFailure.RLock()
	calls = mock.calls.OnInvocationSaveFailure
	mock.lockOnInvocationSaveFailure.RUnlock()
	return calls
}

// ReportAtEnd calls ReportAtEndFunc.
func (mock *buildHealthReporterMock) ReportAtEnd(ctx context.Context, outcome buildOutcome) {
	callInfo := struct {
		Ctx     context.Context
		Outcome buildOutcome
	}{
		Ctx:     ctx,
		Outcome: outcome,
	}
	mock.lockReportAtEnd.Lock()
	mock.calls.ReportAtEnd = append(mock.calls.ReportAtEnd, callInfo)
	mock.lockReportAtEnd.Unlock()
	if mock.ReportAtEndFunc == nil {
		return
	}
	mock.ReportAtEndFunc(ctx, outcome)
}

// ReportAtEndCalls gets all the calls that were made to ReportAtEnd.
// Check the length with:
//
//	len(mockedbuildHealthReporter.ReportAtEndCalls())
func (mock *buildHealthReporterMock) ReportAtEndCalls() []struct {
	Ctx     context.Context
	Outcome buildOutcome
} {
	var calls []struct {
		Ctx     context.Context
		Outcome buildOutcome
	}
	mock.lockReportAtEnd.RLock()
	calls = mock.calls.ReportAtEnd
	mock.lockReportAtEnd.RUnlock()
	return calls
}
