// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package xcode

import (
	"github.com/bitrise-io/bitrise-build-cache-cli/internal/analytics/multiplatform"
	"sync"
)

// Ensure, that relationSenderMock does implement relationSender.
// If this is not the case, regenerate this file with moq.
var _ relationSender = &relationSenderMock{}

// relationSenderMock is a mock implementation of relationSender.
//
//	func TestSomethingThatUsesrelationSender(t *testing.T) {
//
//		// make and configure a mocked relationSender
//		mockedrelationSender := &relationSenderMock{
//			PutInvocationRelationFunc: func(rel multiplatform.InvocationRelation) error {
//				panic("mock out the PutInvocationRelation method")
//			},
//		}
//
//		// use mockedrelationSender in code that requires relationSender
//		// and then make assertions.
//
//	}
type relationSenderMock struct {
	// PutInvocationRelationFunc mocks the PutInvocationRelation method.
	PutInvocationRelationFunc func(rel multiplatform.InvocationRelation) error

	// calls tracks calls to the methods.
	calls struct {
		// PutInvocationRelation holds details about calls to the PutInvocationRelation method.
		PutInvocationRelation []struct {
			// Rel is the rel argument value.
			Rel multiplatform.InvocationRelation
		}
	}
	lockPutInvocationRelation sync.RWMutex
}

// PutInvocationRelation calls PutInvocationRelationFunc.
func (mock *relationSenderMock) PutInvocationRelation(rel multiplatform.InvocationRelation) error {
	callInfo := struct {
		Rel multiplatform.InvocationRelation
	}{
		Rel: rel,
	}
	mock.lockPutInvocationRelation.Lock()
	mock.calls.PutInvocationRelation = append(mock.calls.PutInvocationRelation, callInfo)
	mock.lockPutInvocationRelation.Unlock()
	if mock.PutInvocationRelationFunc == nil {
		var (
			errOut error
		)
		return errOut
	}
	return mock.PutInvocationRelationFunc(rel)
}

// PutInvocationRelationCalls gets all the calls that were made to PutInvocationRelation.
// Check the length with:
//
//	len(mockedrelationSender.PutInvocationRelationCalls())
func (mock *relationSenderMock) PutInvocationRelationCalls() []struct {
	Rel multiplatform.InvocationRelation
} {
	var calls []struct {
		Rel multiplatform.InvocationRelation
	}
	mock.lockPutInvocationRelation.RLock()
	calls = mock.calls.PutInvocationRelation
	mock.lockPutInvocationRelation.RUnlock()
	return calls
}
