// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package xcode

import (
	"github.com/bitrise-io/bitrise-build-cache-cli/v2/internal/invocations"
	"sync"
)

// Ensure, that localInvocationLoggerMock does implement localInvocationLogger.
// If this is not the case, regenerate this file with moq.
var _ localInvocationLogger = &localInvocationLoggerMock{}

// localInvocationLoggerMock is a mock implementation of localInvocationLogger.
//
//	func TestSomethingThatUseslocalInvocationLogger(t *testing.T) {
//
//		// make and configure a mocked localInvocationLogger
//		mockedlocalInvocationLogger := &localInvocationLoggerMock{
//			AppendFunc: func(rec invocations.Record) error {
//				panic("mock out the Append method")
//			},
//		}
//
//		// use mockedlocalInvocationLogger in code that requires localInvocationLogger
//		// and then make assertions.
//
//	}
type localInvocationLoggerMock struct {
	// AppendFunc mocks the Append method.
	AppendFunc func(rec invocations.Record) error

	// calls tracks calls to the methods.
	calls struct {
		// Append holds details about calls to the Append method.
		Append []struct {
			// Rec is the rec argument value.
			Rec invocations.Record
		}
	}
	lockAppend sync.RWMutex
}

// Append calls AppendFunc.
func (mock *localInvocationLoggerMock) Append(rec invocations.Record) error {
	callInfo := struct {
		Rec invocations.Record
	}{
		Rec: rec,
	}
	mock.lockAppend.Lock()
	mock.calls.Append = append(mock.calls.Append, callInfo)
	mock.lockAppend.Unlock()
	if mock.AppendFunc == nil {
		var (
			errOut error
		)
		return errOut
	}
	return mock.AppendFunc(rec)
}

// AppendCalls gets all the calls that were made to Append.
// Check the length with:
//
//	len(mockedlocalInvocationLogger.AppendCalls())
func (mock *localInvocationLoggerMock) AppendCalls() []struct {
	Rec invocations.Record
} {
	var calls []struct {
		Rec invocations.Record
	}
	mock.lockAppend.RLock()
	calls = mock.calls.Append
	mock.lockAppend.RUnlock()
	return calls
}
