// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.0
// source: llvm/session/session.proto

package session

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SetSessionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	InvocationId  string                 `protobuf:"bytes,1,opt,name=invocation_id,json=invocationId,proto3" json:"invocation_id,omitempty"`
	AppSlug       string                 `protobuf:"bytes,2,opt,name=app_slug,json=appSlug,proto3" json:"app_slug,omitempty"`
	BuildSlug     string                 `protobuf:"bytes,3,opt,name=build_slug,json=buildSlug,proto3" json:"build_slug,omitempty"`
	StepSlug      string                 `protobuf:"bytes,4,opt,name=step_slug,json=stepSlug,proto3" json:"step_slug,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetSessionRequest) Reset() {
	*x = SetSessionRequest{}
	mi := &file_llvm_session_session_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetSessionRequest) ProtoMessage() {}

func (x *SetSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_llvm_session_session_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetSessionRequest.ProtoReflect.Descriptor instead.
func (*SetSessionRequest) Descriptor() ([]byte, []int) {
	return file_llvm_session_session_proto_rawDescGZIP(), []int{0}
}

func (x *SetSessionRequest) GetInvocationId() string {
	if x != nil {
		return x.InvocationId
	}
	return ""
}

func (x *SetSessionRequest) GetAppSlug() string {
	if x != nil {
		return x.AppSlug
	}
	return ""
}

func (x *SetSessionRequest) GetBuildSlug() string {
	if x != nil {
		return x.BuildSlug
	}
	return ""
}

func (x *SetSessionRequest) GetStepSlug() string {
	if x != nil {
		return x.StepSlug
	}
	return ""
}

type GetSessionStatsResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	UploadedBytes   int64                  `protobuf:"varint,1,opt,name=uploaded_bytes,json=uploadedBytes,proto3" json:"uploaded_bytes,omitempty"`
	DownloadedBytes int64                  `protobuf:"varint,2,opt,name=downloaded_bytes,json=downloadedBytes,proto3" json:"downloaded_bytes,omitempty"`
	Hits            int64                  `protobuf:"varint,3,opt,name=hits,proto3" json:"hits,omitempty"`
	Misses          int64                  `protobuf:"varint,4,opt,name=misses,proto3" json:"misses,omitempty"`
	Uploads         int64                  `protobuf:"varint,5,opt,name=uploads,proto3" json:"uploads,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *GetSessionStatsResponse) Reset() {
	*x = GetSessionStatsResponse{}
	mi := &file_llvm_session_session_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSessionStatsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSessionStatsResponse) ProtoMessage() {}

func (x *GetSessionStatsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_llvm_session_session_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSessionStatsResponse.ProtoReflect.Descriptor instead.
func (*GetSessionStatsResponse) Descriptor() ([]byte, []int) {
	return file_llvm_session_session_proto_rawDescGZIP(), []int{1}
}

func (x *GetSessionStatsResponse) GetUploadedBytes() int64 {
	if x != nil {
		return x.UploadedBytes
	}
	return 0
}

func (x *GetSessionStatsResponse) GetDownloadedBytes() int64 {
	if x != nil {
		return x.DownloadedBytes
	}
	return 0
}

func (x *GetSessionStatsResponse) GetHits() int64 {
	if x != nil {
		return x.Hits
	}
	return 0
}

func (x *GetSessionStatsResponse) GetMisses() int64 {
	if x != nil {
		return x.Misses
	}
	return 0
}

func (x *GetSessionStatsResponse) GetUploads() int64 {
	if x != nil {
		return x.Uploads
	}
	return 0
}

var File_llvm_session_session_proto protoreflect.FileDescriptor

const file_llvm_session_session_proto_rawDesc = "" +
	"\n" +
	"\x1allvm/session/session.proto\x12\asession\x1a\x1bgoogle/protobuf/empty.proto\"\x8f\x01\n" +
	"\x11SetSessionRequest\x12#\n" +
	"\rinvocation_id\x18\x01 \x01(\tR\finvocationId\x12\x19\n" +
	"\bapp_slug\x18\x02 \x01(\tR\aappSlug\x12\x1d\n" +
	"\n" +
	"build_slug\x18\x03 \x01(\tR\tbuildSlug\x12\x1b\n" +
	"\tstep_slug\x18\x04 \x01(\tR\bstepSlug\"\xb1\x01\n" +
	"\x17GetSessionStatsResponse\x12%\n" +
	"\x0euploaded_bytes\x18\x01 \x01(\x03R\ruploadedBytes\x12)\n" +
	"\x10downloaded_bytes\x18\x02 \x01(\x03R\x0fdownloadedBytes\x12\x12\n" +
	"\x04hits\x18\x03 \x01(\x03R\x04hits\x12\x16\n" +
	"\x06misses\x18\x04 \x01(\x03R\x06misses\x12\x18\n" +
	"\auploads\x18\x05 \x01(\x03R\auploads2\x9c\x01\n" +
	"\aSession\x12B\n" +
	"\n" +
	"SetSession\x12\x1a.session.SetSessionRequest\x1a\x16.google.protobuf.Empty\"\x00\x12M\n" +
	"\x0fGetSessionStats\x12\x16.google.protobuf.Empty\x1a .session.GetSessionStatsResponse\"\x00BDZBgithub.com/bitrise-io/bitrise-build-cache-cli/llvm/session;sessionb\x06proto3"

var (
	file_llvm_session_session_proto_rawDescOnce sync.Once
	file_llvm_session_session_proto_rawDescData []byte
)

func file_llvm_session_session_proto_rawDescGZIP() []byte {
	file_llvm_session_session_proto_rawDescOnce.Do(func() {
		file_llvm_session_session_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_llvm_session_session_proto_rawDesc), len(file_llvm_session_session_proto_rawDesc)))
	})
	return file_llvm_session_session_proto_rawDescData
}

var file_llvm_session_session_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_llvm_session_session_proto_goTypes = []any{
	(*SetSessionRequest)(nil),       // 0: session.SetSessionRequest
	(*GetSessionStatsResponse)(nil), // 1: session.GetSessionStatsResponse
	(*emptypb.Empty)(nil),           // 2: google.protobuf.Empty
}
var file_llvm_session_session_proto_depIdxs = []int32{
	0, // 0: session.Session.SetSession:input_type -> session.SetSessionRequest
	2, // 1: session.Session.GetSessionStats:input_type -> google.protobuf.Empty
	2, // 2: session.Session.SetSession:output_type -> google.protobuf.Empty
	1, // 3: session.Session.GetSessionStats:output_type -> session.GetSessionStatsResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_llvm_session_session_proto_init() }
func file_llvm_session_session_proto_init() {
	if File_llvm_session_session_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_llvm_session_session_proto_rawDesc), len(file_llvm_session_session_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_llvm_session_session_proto_goTypes,
		DependencyIndexes: file_llvm_session_session_proto_depIdxs,
		MessageInfos:      file_llvm_session_session_proto_msgTypes,
	}.Build()
	File_llvm_session_session_proto = out.File
	file_llvm_session_session_proto_goTypes = nil
	file_llvm_session_session_proto_depIdxs = nil
}
