// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        v5.29.3
// source: llvm/session/session.proto

package session

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SetSessionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	InvocationId  string                 `protobuf:"bytes,1,opt,name=invocation_id,json=invocationId,proto3" json:"invocation_id,omitempty"`
	BuildSlug     string                 `protobuf:"bytes,2,opt,name=build_slug,json=buildSlug,proto3" json:"build_slug,omitempty"`
	StepSlug      string                 `protobuf:"bytes,3,opt,name=step_slug,json=stepSlug,proto3" json:"step_slug,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetSessionRequest) Reset() {
	*x = SetSessionRequest{}
	mi := &file_llvm_session_session_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetSessionRequest) ProtoMessage() {}

func (x *SetSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_llvm_session_session_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetSessionRequest.ProtoReflect.Descriptor instead.
func (*SetSessionRequest) Descriptor() ([]byte, []int) {
	return file_llvm_session_session_proto_rawDescGZIP(), []int{0}
}

func (x *SetSessionRequest) GetInvocationId() string {
	if x != nil {
		return x.InvocationId
	}
	return ""
}

func (x *SetSessionRequest) GetBuildSlug() string {
	if x != nil {
		return x.BuildSlug
	}
	return ""
}

func (x *SetSessionRequest) GetStepSlug() string {
	if x != nil {
		return x.StepSlug
	}
	return ""
}

var File_llvm_session_session_proto protoreflect.FileDescriptor

const file_llvm_session_session_proto_rawDesc = "" +
	"\n" +
	"\x1allvm/session/session.proto\x12\asession\x1a\x1bgoogle/protobuf/empty.proto\"t\n" +
	"\x11SetSessionRequest\x12#\n" +
	"\rinvocation_id\x18\x01 \x01(\tR\finvocationId\x12\x1d\n" +
	"\n" +
	"build_slug\x18\x02 \x01(\tR\tbuildSlug\x12\x1b\n" +
	"\tstep_slug\x18\x03 \x01(\tR\bstepSlug2M\n" +
	"\aSession\x12B\n" +
	"\n" +
	"SetSession\x12\x1a.session.SetSessionRequest\x1a\x16.google.protobuf.Empty\"\x00BDZBgithub.com/bitrise-io/bitrise-build-cache-cli/llvm/session;sessionb\x06proto3"

var (
	file_llvm_session_session_proto_rawDescOnce sync.Once
	file_llvm_session_session_proto_rawDescData []byte
)

func file_llvm_session_session_proto_rawDescGZIP() []byte {
	file_llvm_session_session_proto_rawDescOnce.Do(func() {
		file_llvm_session_session_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_llvm_session_session_proto_rawDesc), len(file_llvm_session_session_proto_rawDesc)))
	})
	return file_llvm_session_session_proto_rawDescData
}

var file_llvm_session_session_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_llvm_session_session_proto_goTypes = []any{
	(*SetSessionRequest)(nil), // 0: session.SetSessionRequest
	(*emptypb.Empty)(nil),     // 1: google.protobuf.Empty
}
var file_llvm_session_session_proto_depIdxs = []int32{
	0, // 0: session.Session.SetSession:input_type -> session.SetSessionRequest
	1, // 1: session.Session.SetSession:output_type -> google.protobuf.Empty
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_llvm_session_session_proto_init() }
func file_llvm_session_session_proto_init() {
	if File_llvm_session_session_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_llvm_session_session_proto_rawDesc), len(file_llvm_session_session_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_llvm_session_session_proto_goTypes,
		DependencyIndexes: file_llvm_session_session_proto_depIdxs,
		MessageInfos:      file_llvm_session_session_proto_msgTypes,
	}.Build()
	File_llvm_session_session_proto = out.File
	file_llvm_session_session_proto_goTypes = nil
	file_llvm_session_session_proto_depIdxs = nil
}
