// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.0
// source: llvm/session/session.proto

package session

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SetSessionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	InvocationId  string                 `protobuf:"bytes,1,opt,name=invocation_id,json=invocationId,proto3" json:"invocation_id,omitempty"`
	AppSlug       string                 `protobuf:"bytes,2,opt,name=app_slug,json=appSlug,proto3" json:"app_slug,omitempty"`
	BuildSlug     string                 `protobuf:"bytes,3,opt,name=build_slug,json=buildSlug,proto3" json:"build_slug,omitempty"`
	StepSlug      string                 `protobuf:"bytes,4,opt,name=step_slug,json=stepSlug,proto3" json:"step_slug,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetSessionRequest) Reset() {
	*x = SetSessionRequest{}
	mi := &file_llvm_session_session_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetSessionRequest) ProtoMessage() {}

func (x *SetSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_llvm_session_session_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetSessionRequest.ProtoReflect.Descriptor instead.
func (*SetSessionRequest) Descriptor() ([]byte, []int) {
	return file_llvm_session_session_proto_rawDescGZIP(), []int{0}
}

func (x *SetSessionRequest) GetInvocationId() string {
	if x != nil {
		return x.InvocationId
	}
	return ""
}

func (x *SetSessionRequest) GetAppSlug() string {
	if x != nil {
		return x.AppSlug
	}
	return ""
}

func (x *SetSessionRequest) GetBuildSlug() string {
	if x != nil {
		return x.BuildSlug
	}
	return ""
}

func (x *SetSessionRequest) GetStepSlug() string {
	if x != nil {
		return x.StepSlug
	}
	return ""
}

type EndSessionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	InvocationId  string                 `protobuf:"bytes,1,opt,name=invocation_id,json=invocationId,proto3" json:"invocation_id,omitempty"`
	EndTimeUnixMs int64                  `protobuf:"varint,2,opt,name=end_time_unix_ms,json=endTimeUnixMs,proto3" json:"end_time_unix_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EndSessionRequest) Reset() {
	*x = EndSessionRequest{}
	mi := &file_llvm_session_session_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EndSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EndSessionRequest) ProtoMessage() {}

func (x *EndSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_llvm_session_session_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EndSessionRequest.ProtoReflect.Descriptor instead.
func (*EndSessionRequest) Descriptor() ([]byte, []int) {
	return file_llvm_session_session_proto_rawDescGZIP(), []int{1}
}

func (x *EndSessionRequest) GetInvocationId() string {
	if x != nil {
		return x.InvocationId
	}
	return ""
}

func (x *EndSessionRequest) GetEndTimeUnixMs() int64 {
	if x != nil {
		return x.EndTimeUnixMs
	}
	return 0
}

type GetSessionStatsResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	UploadedBytes   int64                  `protobuf:"varint,1,opt,name=uploaded_bytes,json=uploadedBytes,proto3" json:"uploaded_bytes,omitempty"`
	DownloadedBytes int64                  `protobuf:"varint,2,opt,name=downloaded_bytes,json=downloadedBytes,proto3" json:"downloaded_bytes,omitempty"`
	Hits            int64                  `protobuf:"varint,3,opt,name=hits,proto3" json:"hits,omitempty"`
	Misses          int64                  `protobuf:"varint,4,opt,name=misses,proto3" json:"misses,omitempty"`
	Uploads         int64                  `protobuf:"varint,5,opt,name=uploads,proto3" json:"uploads,omitempty"`
	KvHits          int64                  `protobuf:"varint,6,opt,name=kv_hits,json=kvHits,proto3" json:"kv_hits,omitempty"`
	KvMisses        int64                  `protobuf:"varint,7,opt,name=kv_misses,json=kvMisses,proto3" json:"kv_misses,omitempty"`
	KvUploadedBytes int64                  `protobuf:"varint,8,opt,name=kv_uploaded_bytes,json=kvUploadedBytes,proto3" json:"kv_uploaded_bytes,omitempty"`
	Errors          int64                  `protobuf:"varint,9,opt,name=errors,proto3" json:"errors,omitempty"`
	FirstError      string                 `protobuf:"bytes,10,opt,name=first_error,json=firstError,proto3" json:"first_error,omitempty"`
	CacheBlobStats  *CacheBlobStats        `protobuf:"bytes,11,opt,name=cache_blob_stats,json=cacheBlobStats,proto3,oneof" json:"cache_blob_stats,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *GetSessionStatsResponse) Reset() {
	*x = GetSessionStatsResponse{}
	mi := &file_llvm_session_session_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSessionStatsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSessionStatsResponse) ProtoMessage() {}

func (x *GetSessionStatsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_llvm_session_session_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSessionStatsResponse.ProtoReflect.Descriptor instead.
func (*GetSessionStatsResponse) Descriptor() ([]byte, []int) {
	return file_llvm_session_session_proto_rawDescGZIP(), []int{2}
}

func (x *GetSessionStatsResponse) GetUploadedBytes() int64 {
	if x != nil {
		return x.UploadedBytes
	}
	return 0
}

func (x *GetSessionStatsResponse) GetDownloadedBytes() int64 {
	if x != nil {
		return x.DownloadedBytes
	}
	return 0
}

func (x *GetSessionStatsResponse) GetHits() int64 {
	if x != nil {
		return x.Hits
	}
	return 0
}

func (x *GetSessionStatsResponse) GetMisses() int64 {
	if x != nil {
		return x.Misses
	}
	return 0
}

func (x *GetSessionStatsResponse) GetUploads() int64 {
	if x != nil {
		return x.Uploads
	}
	return 0
}

func (x *GetSessionStatsResponse) GetKvHits() int64 {
	if x != nil {
		return x.KvHits
	}
	return 0
}

func (x *GetSessionStatsResponse) GetKvMisses() int64 {
	if x != nil {
		return x.KvMisses
	}
	return 0
}

func (x *GetSessionStatsResponse) GetKvUploadedBytes() int64 {
	if x != nil {
		return x.KvUploadedBytes
	}
	return 0
}

func (x *GetSessionStatsResponse) GetErrors() int64 {
	if x != nil {
		return x.Errors
	}
	return 0
}

func (x *GetSessionStatsResponse) GetFirstError() string {
	if x != nil {
		return x.FirstError
	}
	return ""
}

func (x *GetSessionStatsResponse) GetCacheBlobStats() *CacheBlobStats {
	if x != nil {
		return x.CacheBlobStats
	}
	return nil
}

// `counts` is one longer than `boundaries`: the last entry is the overflow bucket. Boundaries
// travel with the payload so the scale can be retuned in a CLI release without a backend
// deploy, and so older invocations keep rendering on their own axis.
type Histogram struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Boundaries    []int64                `protobuf:"varint,1,rep,packed,name=boundaries,proto3" json:"boundaries,omitempty"`
	Counts        []int64                `protobuf:"varint,2,rep,packed,name=counts,proto3" json:"counts,omitempty"`
	Count         int64                  `protobuf:"varint,3,opt,name=count,proto3" json:"count,omitempty"`
	Sum           int64                  `protobuf:"varint,4,opt,name=sum,proto3" json:"sum,omitempty"`
	Min           int64                  `protobuf:"varint,5,opt,name=min,proto3" json:"min,omitempty"`
	Max           int64                  `protobuf:"varint,6,opt,name=max,proto3" json:"max,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Histogram) Reset() {
	*x = Histogram{}
	mi := &file_llvm_session_session_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Histogram) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Histogram) ProtoMessage() {}

func (x *Histogram) ProtoReflect() protoreflect.Message {
	mi := &file_llvm_session_session_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Histogram.ProtoReflect.Descriptor instead.
func (*Histogram) Descriptor() ([]byte, []int) {
	return file_llvm_session_session_proto_rawDescGZIP(), []int{3}
}

func (x *Histogram) GetBoundaries() []int64 {
	if x != nil {
		return x.Boundaries
	}
	return nil
}

func (x *Histogram) GetCounts() []int64 {
	if x != nil {
		return x.Counts
	}
	return nil
}

func (x *Histogram) GetCount() int64 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *Histogram) GetSum() int64 {
	if x != nil {
		return x.Sum
	}
	return 0
}

func (x *Histogram) GetMin() int64 {
	if x != nil {
		return x.Min
	}
	return 0
}

func (x *Histogram) GetMax() int64 {
	if x != nil {
		return x.Max
	}
	return 0
}

// Percentiles are exact, computed from retained per-op samples. The histogram is what makes them
// mergeable across invocations, since percentiles themselves cannot be summed.
type ThroughputStats struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Histogram        *Histogram             `protobuf:"bytes,1,opt,name=histogram,proto3" json:"histogram,omitempty"`
	P10BytesPerSec   int64                  `protobuf:"varint,2,opt,name=p10_bytes_per_sec,json=p10BytesPerSec,proto3" json:"p10_bytes_per_sec,omitempty"`
	P50BytesPerSec   int64                  `protobuf:"varint,3,opt,name=p50_bytes_per_sec,json=p50BytesPerSec,proto3" json:"p50_bytes_per_sec,omitempty"`
	P90BytesPerSec   int64                  `protobuf:"varint,4,opt,name=p90_bytes_per_sec,json=p90BytesPerSec,proto3" json:"p90_bytes_per_sec,omitempty"`
	MinBlobBytes     int64                  `protobuf:"varint,5,opt,name=min_blob_bytes,json=minBlobBytes,proto3" json:"min_blob_bytes,omitempty"`
	ExcludedSmallOps int64                  `protobuf:"varint,6,opt,name=excluded_small_ops,json=excludedSmallOps,proto3" json:"excluded_small_ops,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ThroughputStats) Reset() {
	*x = ThroughputStats{}
	mi := &file_llvm_session_session_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ThroughputStats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ThroughputStats) ProtoMessage() {}

func (x *ThroughputStats) ProtoReflect() protoreflect.Message {
	mi := &file_llvm_session_session_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ThroughputStats.ProtoReflect.Descriptor instead.
func (*ThroughputStats) Descriptor() ([]byte, []int) {
	return file_llvm_session_session_proto_rawDescGZIP(), []int{4}
}

func (x *ThroughputStats) GetHistogram() *Histogram {
	if x != nil {
		return x.Histogram
	}
	return nil
}

func (x *ThroughputStats) GetP10BytesPerSec() int64 {
	if x != nil {
		return x.P10BytesPerSec
	}
	return 0
}

func (x *ThroughputStats) GetP50BytesPerSec() int64 {
	if x != nil {
		return x.P50BytesPerSec
	}
	return 0
}

func (x *ThroughputStats) GetP90BytesPerSec() int64 {
	if x != nil {
		return x.P90BytesPerSec
	}
	return 0
}

func (x *ThroughputStats) GetMinBlobBytes() int64 {
	if x != nil {
		return x.MinBlobBytes
	}
	return 0
}

func (x *ThroughputStats) GetExcludedSmallOps() int64 {
	if x != nil {
		return x.ExcludedSmallOps
	}
	return 0
}

// op_count + error_count + miss_count reconciles against latency_ms.count;
// skipped_already_saved_count stays out of that sum because it is not a transfer.
type BlobStats struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	OpCount    int64                  `protobuf:"varint,1,opt,name=op_count,json=opCount,proto3" json:"op_count,omitempty"`
	ErrorCount int64                  `protobuf:"varint,2,opt,name=error_count,json=errorCount,proto3" json:"error_count,omitempty"`
	// Counted rather than timed: a miss is a cheap round trip and would pull the latency
	// distribution down. Downloads only.
	MissCount int64 `protobuf:"varint,3,opt,name=miss_count,json=missCount,proto3" json:"miss_count,omitempty"`
	// Uploads only: the blob was already stored in this session, so nothing went over the wire.
	SkippedAlreadySavedCount int64            `protobuf:"varint,4,opt,name=skipped_already_saved_count,json=skippedAlreadySavedCount,proto3" json:"skipped_already_saved_count,omitempty"`
	BytesTotal               int64            `protobuf:"varint,5,opt,name=bytes_total,json=bytesTotal,proto3" json:"bytes_total,omitempty"`
	LatencyMs                *Histogram       `protobuf:"bytes,6,opt,name=latency_ms,json=latencyMs,proto3" json:"latency_ms,omitempty"`
	SizeBytes                *Histogram       `protobuf:"bytes,7,opt,name=size_bytes,json=sizeBytes,proto3" json:"size_bytes,omitempty"`
	Throughput               *ThroughputStats `protobuf:"bytes,8,opt,name=throughput,proto3" json:"throughput,omitempty"`
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *BlobStats) Reset() {
	*x = BlobStats{}
	mi := &file_llvm_session_session_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BlobStats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlobStats) ProtoMessage() {}

func (x *BlobStats) ProtoReflect() protoreflect.Message {
	mi := &file_llvm_session_session_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlobStats.ProtoReflect.Descriptor instead.
func (*BlobStats) Descriptor() ([]byte, []int) {
	return file_llvm_session_session_proto_rawDescGZIP(), []int{5}
}

func (x *BlobStats) GetOpCount() int64 {
	if x != nil {
		return x.OpCount
	}
	return 0
}

func (x *BlobStats) GetErrorCount() int64 {
	if x != nil {
		return x.ErrorCount
	}
	return 0
}

func (x *BlobStats) GetMissCount() int64 {
	if x != nil {
		return x.MissCount
	}
	return 0
}

func (x *BlobStats) GetSkippedAlreadySavedCount() int64 {
	if x != nil {
		return x.SkippedAlreadySavedCount
	}
	return 0
}

func (x *BlobStats) GetBytesTotal() int64 {
	if x != nil {
		return x.BytesTotal
	}
	return 0
}

func (x *BlobStats) GetLatencyMs() *Histogram {
	if x != nil {
		return x.LatencyMs
	}
	return nil
}

func (x *BlobStats) GetSizeBytes() *Histogram {
	if x != nil {
		return x.SizeBytes
	}
	return nil
}

func (x *BlobStats) GetThroughput() *ThroughputStats {
	if x != nil {
		return x.Throughput
	}
	return nil
}

type CacheBlobStats struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SchemaVersion int32                  `protobuf:"varint,1,opt,name=schema_version,json=schemaVersion,proto3" json:"schema_version,omitempty"`
	Upload        *BlobStats             `protobuf:"bytes,2,opt,name=upload,proto3" json:"upload,omitempty"`
	Download      *BlobStats             `protobuf:"bytes,3,opt,name=download,proto3" json:"download,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CacheBlobStats) Reset() {
	*x = CacheBlobStats{}
	mi := &file_llvm_session_session_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CacheBlobStats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CacheBlobStats) ProtoMessage() {}

func (x *CacheBlobStats) ProtoReflect() protoreflect.Message {
	mi := &file_llvm_session_session_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CacheBlobStats.ProtoReflect.Descriptor instead.
func (*CacheBlobStats) Descriptor() ([]byte, []int) {
	return file_llvm_session_session_proto_rawDescGZIP(), []int{6}
}

func (x *CacheBlobStats) GetSchemaVersion() int32 {
	if x != nil {
		return x.SchemaVersion
	}
	return 0
}

func (x *CacheBlobStats) GetUpload() *BlobStats {
	if x != nil {
		return x.Upload
	}
	return nil
}

func (x *CacheBlobStats) GetDownload() *BlobStats {
	if x != nil {
		return x.Download
	}
	return nil
}

var File_llvm_session_session_proto protoreflect.FileDescriptor

const file_llvm_session_session_proto_rawDesc = "" +
	"\n" +
	"\x1allvm/session/session.proto\x12\asession\x1a\x1bgoogle/protobuf/empty.proto\"\x8f\x01\n" +
	"\x11SetSessionRequest\x12#\n" +
	"\rinvocation_id\x18\x01 \x01(\tR\finvocationId\x12\x19\n" +
	"\bapp_slug\x18\x02 \x01(\tR\aappSlug\x12\x1d\n" +
	"\n" +
	"build_slug\x18\x03 \x01(\tR\tbuildSlug\x12\x1b\n" +
	"\tstep_slug\x18\x04 \x01(\tR\bstepSlug\"a\n" +
	"\x11EndSessionRequest\x12#\n" +
	"\rinvocation_id\x18\x01 \x01(\tR\finvocationId\x12'\n" +
	"\x10end_time_unix_ms\x18\x02 \x01(\x03R\rendTimeUnixMs\"\xa9\x03\n" +
	"\x17GetSessionStatsResponse\x12%\n" +
	"\x0euploaded_bytes\x18\x01 \x01(\x03R\ruploadedBytes\x12)\n" +
	"\x10downloaded_bytes\x18\x02 \x01(\x03R\x0fdownloadedBytes\x12\x12\n" +
	"\x04hits\x18\x03 \x01(\x03R\x04hits\x12\x16\n" +
	"\x06misses\x18\x04 \x01(\x03R\x06misses\x12\x18\n" +
	"\auploads\x18\x05 \x01(\x03R\auploads\x12\x17\n" +
	"\akv_hits\x18\x06 \x01(\x03R\x06kvHits\x12\x1b\n" +
	"\tkv_misses\x18\a \x01(\x03R\bkvMisses\x12*\n" +
	"\x11kv_uploaded_bytes\x18\b \x01(\x03R\x0fkvUploadedBytes\x12\x16\n" +
	"\x06errors\x18\t \x01(\x03R\x06errors\x12\x1f\n" +
	"\vfirst_error\x18\n" +
	" \x01(\tR\n" +
	"firstError\x12F\n" +
	"\x10cache_blob_stats\x18\v \x01(\v2\x17.session.CacheBlobStatsH\x00R\x0ecacheBlobStats\x88\x01\x01B\x13\n" +
	"\x11_cache_blob_stats\"\x8f\x01\n" +
	"\tHistogram\x12\x1e\n" +
	"\n" +
	"boundaries\x18\x01 \x03(\x03R\n" +
	"boundaries\x12\x16\n" +
	"\x06counts\x18\x02 \x03(\x03R\x06counts\x12\x14\n" +
	"\x05count\x18\x03 \x01(\x03R\x05count\x12\x10\n" +
	"\x03sum\x18\x04 \x01(\x03R\x03sum\x12\x10\n" +
	"\x03min\x18\x05 \x01(\x03R\x03min\x12\x10\n" +
	"\x03max\x18\x06 \x01(\x03R\x03max\"\x98\x02\n" +
	"\x0fThroughputStats\x120\n" +
	"\thistogram\x18\x01 \x01(\v2\x12.session.HistogramR\thistogram\x12)\n" +
	"\x11p10_bytes_per_sec\x18\x02 \x01(\x03R\x0ep10BytesPerSec\x12)\n" +
	"\x11p50_bytes_per_sec\x18\x03 \x01(\x03R\x0ep50BytesPerSec\x12)\n" +
	"\x11p90_bytes_per_sec\x18\x04 \x01(\x03R\x0ep90BytesPerSec\x12$\n" +
	"\x0emin_blob_bytes\x18\x05 \x01(\x03R\fminBlobBytes\x12,\n" +
	"\x12excluded_small_ops\x18\x06 \x01(\x03R\x10excludedSmallOps\"\xe6\x02\n" +
	"\tBlobStats\x12\x19\n" +
	"\bop_count\x18\x01 \x01(\x03R\aopCount\x12\x1f\n" +
	"\verror_count\x18\x02 \x01(\x03R\n" +
	"errorCount\x12\x1d\n" +
	"\n" +
	"miss_count\x18\x03 \x01(\x03R\tmissCount\x12=\n" +
	"\x1bskipped_already_saved_count\x18\x04 \x01(\x03R\x18skippedAlreadySavedCount\x12\x1f\n" +
	"\vbytes_total\x18\x05 \x01(\x03R\n" +
	"bytesTotal\x121\n" +
	"\n" +
	"latency_ms\x18\x06 \x01(\v2\x12.session.HistogramR\tlatencyMs\x121\n" +
	"\n" +
	"size_bytes\x18\a \x01(\v2\x12.session.HistogramR\tsizeBytes\x128\n" +
	"\n" +
	"throughput\x18\b \x01(\v2\x18.session.ThroughputStatsR\n" +
	"throughput\"\x93\x01\n" +
	"\x0eCacheBlobStats\x12%\n" +
	"\x0eschema_version\x18\x01 \x01(\x05R\rschemaVersion\x12*\n" +
	"\x06upload\x18\x02 \x01(\v2\x12.session.BlobStatsR\x06upload\x12.\n" +
	"\bdownload\x18\x03 \x01(\v2\x12.session.BlobStatsR\bdownload2\xe0\x01\n" +
	"\aSession\x12B\n" +
	"\n" +
	"SetSession\x12\x1a.session.SetSessionRequest\x1a\x16.google.protobuf.Empty\"\x00\x12B\n" +
	"\n" +
	"EndSession\x12\x1a.session.EndSessionRequest\x1a\x16.google.protobuf.Empty\"\x00\x12M\n" +
	"\x0fGetSessionStats\x12\x16.google.protobuf.Empty\x1a .session.GetSessionStatsResponse\"\x00BGZEgithub.com/bitrise-io/bitrise-build-cache-cli/v3/llvm/session;sessionb\x06proto3"

var (
	file_llvm_session_session_proto_rawDescOnce sync.Once
	file_llvm_session_session_proto_rawDescData []byte
)

func file_llvm_session_session_proto_rawDescGZIP() []byte {
	file_llvm_session_session_proto_rawDescOnce.Do(func() {
		file_llvm_session_session_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_llvm_session_session_proto_rawDesc), len(file_llvm_session_session_proto_rawDesc)))
	})
	return file_llvm_session_session_proto_rawDescData
}

var file_llvm_session_session_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_llvm_session_session_proto_goTypes = []any{
	(*SetSessionRequest)(nil),       // 0: session.SetSessionRequest
	(*EndSessionRequest)(nil),       // 1: session.EndSessionRequest
	(*GetSessionStatsResponse)(nil), // 2: session.GetSessionStatsResponse
	(*Histogram)(nil),               // 3: session.Histogram
	(*ThroughputStats)(nil),         // 4: session.ThroughputStats
	(*BlobStats)(nil),               // 5: session.BlobStats
	(*CacheBlobStats)(nil),          // 6: session.CacheBlobStats
	(*emptypb.Empty)(nil),           // 7: google.protobuf.Empty
}
var file_llvm_session_session_proto_depIdxs = []int32{
	6,  // 0: session.GetSessionStatsResponse.cache_blob_stats:type_name -> session.CacheBlobStats
	3,  // 1: session.ThroughputStats.histogram:type_name -> session.Histogram
	3,  // 2: session.BlobStats.latency_ms:type_name -> session.Histogram
	3,  // 3: session.BlobStats.size_bytes:type_name -> session.Histogram
	4,  // 4: session.BlobStats.throughput:type_name -> session.ThroughputStats
	5,  // 5: session.CacheBlobStats.upload:type_name -> session.BlobStats
	5,  // 6: session.CacheBlobStats.download:type_name -> session.BlobStats
	0,  // 7: session.Session.SetSession:input_type -> session.SetSessionRequest
	1,  // 8: session.Session.EndSession:input_type -> session.EndSessionRequest
	7,  // 9: session.Session.GetSessionStats:input_type -> google.protobuf.Empty
	7,  // 10: session.Session.SetSession:output_type -> google.protobuf.Empty
	7,  // 11: session.Session.EndSession:output_type -> google.protobuf.Empty
	2,  // 12: session.Session.GetSessionStats:output_type -> session.GetSessionStatsResponse
	10, // [10:13] is the sub-list for method output_type
	7,  // [7:10] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_llvm_session_session_proto_init() }
func file_llvm_session_session_proto_init() {
	if File_llvm_session_session_proto != nil {
		return
	}
	file_llvm_session_session_proto_msgTypes[2].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_llvm_session_session_proto_rawDesc), len(file_llvm_session_session_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_llvm_session_session_proto_goTypes,
		DependencyIndexes: file_llvm_session_session_proto_depIdxs,
		MessageInfos:      file_llvm_session_session_proto_msgTypes,
	}.Build()
	File_llvm_session_session_proto = out.File
	file_llvm_session_session_proto_goTypes = nil
	file_llvm_session_session_proto_depIdxs = nil
}
