// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package mocks

import (
	"github.com/bitrise-io/bitrise-build-cache-cli/cmd/xcode"
	"github.com/bitrise-io/bitrise-build-cache-cli/internal/utils"
	"github.com/bitrise-io/go-utils/v2/log"
	"sync"
)

// Ensure, that XcelerateConfigMock does implement xcode.XcelerateConfig.
// If this is not the case, regenerate this file with moq.
var _ xcode.XcelerateConfig = &XcelerateConfigMock{}

// XcelerateConfigMock is a mock implementation of xcode.XcelerateConfig.
//
//	func TestSomethingThatUsesXcelerateConfig(t *testing.T) {
//
//		// make and configure a mocked xcode.XcelerateConfig
//		mockedXcelerateConfig := &XcelerateConfigMock{
//			SaveFunc: func(logger log.Logger, os utils.OsProxy, encoderFactory utils.EncoderFactory) error {
//				panic("mock out the Save method")
//			},
//		}
//
//		// use mockedXcelerateConfig in code that requires xcode.XcelerateConfig
//		// and then make assertions.
//
//	}
type XcelerateConfigMock struct {
	// SaveFunc mocks the Save method.
	SaveFunc func(logger log.Logger, os utils.OsProxy, encoderFactory utils.EncoderFactory) error

	// calls tracks calls to the methods.
	calls struct {
		// Save holds details about calls to the Save method.
		Save []struct {
			// Logger is the logger argument value.
			Logger log.Logger
			// Os is the os argument value.
			Os utils.OsProxy
			// EncoderFactory is the encoderFactory argument value.
			EncoderFactory utils.EncoderFactory
		}
	}
	lockSave sync.RWMutex
}

// Save calls SaveFunc.
func (mock *XcelerateConfigMock) Save(logger log.Logger, os utils.OsProxy, encoderFactory utils.EncoderFactory) error {
	callInfo := struct {
		Logger         log.Logger
		Os             utils.OsProxy
		EncoderFactory utils.EncoderFactory
	}{
		Logger:         logger,
		Os:             os,
		EncoderFactory: encoderFactory,
	}
	mock.lockSave.Lock()
	mock.calls.Save = append(mock.calls.Save, callInfo)
	mock.lockSave.Unlock()
	if mock.SaveFunc == nil {
		var (
			errOut error
		)
		return errOut
	}
	return mock.SaveFunc(logger, os, encoderFactory)
}

// SaveCalls gets all the calls that were made to Save.
// Check the length with:
//
//	len(mockedXcelerateConfig.SaveCalls())
func (mock *XcelerateConfigMock) SaveCalls() []struct {
	Logger         log.Logger
	Os             utils.OsProxy
	EncoderFactory utils.EncoderFactory
} {
	var calls []struct {
		Logger         log.Logger
		Os             utils.OsProxy
		EncoderFactory utils.EncoderFactory
	}
	mock.lockSave.RLock()
	calls = mock.calls.Save
	mock.lockSave.RUnlock()
	return calls
}
