// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package mocks

import (
	"github.com/bitrise-io/bitrise-build-cache-cli/cmd/xcode"
	xa "github.com/bitrise-io/bitrise-build-cache-cli/internal/xcelerate/analytics"
	"sync"
)

// Ensure, that InvocationSaverMock does implement xcode.InvocationSaver.
// If this is not the case, regenerate this file with moq.
var _ xcode.InvocationSaver = &InvocationSaverMock{}

// InvocationSaverMock is a mock implementation of xcode.InvocationSaver.
//
//	func TestSomethingThatUsesInvocationSaver(t *testing.T) {
//
//		// make and configure a mocked xcode.InvocationSaver
//		mockedInvocationSaver := &InvocationSaverMock{
//			PutInvocationFunc: func(inv xa.Invocation) error {
//				panic("mock out the PutInvocation method")
//			},
//		}
//
//		// use mockedInvocationSaver in code that requires xcode.InvocationSaver
//		// and then make assertions.
//
//	}
type InvocationSaverMock struct {
	// PutInvocationFunc mocks the PutInvocation method.
	PutInvocationFunc func(inv xa.Invocation) error

	// calls tracks calls to the methods.
	calls struct {
		// PutInvocation holds details about calls to the PutInvocation method.
		PutInvocation []struct {
			// Inv is the inv argument value.
			Inv xa.Invocation
		}
	}
	lockPutInvocation sync.RWMutex
}

// PutInvocation calls PutInvocationFunc.
func (mock *InvocationSaverMock) PutInvocation(inv xa.Invocation) error {
	callInfo := struct {
		Inv xa.Invocation
	}{
		Inv: inv,
	}
	mock.lockPutInvocation.Lock()
	mock.calls.PutInvocation = append(mock.calls.PutInvocation, callInfo)
	mock.lockPutInvocation.Unlock()
	if mock.PutInvocationFunc == nil {
		var (
			errOut error
		)
		return errOut
	}
	return mock.PutInvocationFunc(inv)
}

// PutInvocationCalls gets all the calls that were made to PutInvocation.
// Check the length with:
//
//	len(mockedInvocationSaver.PutInvocationCalls())
func (mock *InvocationSaverMock) PutInvocationCalls() []struct {
	Inv xa.Invocation
} {
	var calls []struct {
		Inv xa.Invocation
	}
	mock.lockPutInvocation.RLock()
	calls = mock.calls.PutInvocation
	mock.lockPutInvocation.RUnlock()
	return calls
}
