//===--- compilation_caching_kv.proto - Key/Value service definition ------===//
//
// Part of the LLVM Project, under the Apache License v2.0 with LLVM Exceptions.
// See https://llvm.org/LICENSE.txt for license information.
// SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
//
//===----------------------------------------------------------------------===//

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        v5.29.3
// source: llvm/kv/compilation_caching_kv.proto

package llvmkv

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetValueResponse_Outcome int32

const (
	GetValueResponse_ERROR         GetValueResponse_Outcome = 0 // if unset, we'll get error
	GetValueResponse_KEY_NOT_FOUND GetValueResponse_Outcome = 1
	GetValueResponse_SUCCESS       GetValueResponse_Outcome = 2
)

// Enum value maps for GetValueResponse_Outcome.
var (
	GetValueResponse_Outcome_name = map[int32]string{
		0: "ERROR",
		1: "KEY_NOT_FOUND",
		2: "SUCCESS",
	}
	GetValueResponse_Outcome_value = map[string]int32{
		"ERROR":         0,
		"KEY_NOT_FOUND": 1,
		"SUCCESS":       2,
	}
)

func (x GetValueResponse_Outcome) Enum() *GetValueResponse_Outcome {
	p := new(GetValueResponse_Outcome)
	*p = x
	return p
}

func (x GetValueResponse_Outcome) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (GetValueResponse_Outcome) Descriptor() protoreflect.EnumDescriptor {
	return file_llvm_kv_compilation_caching_kv_proto_enumTypes[0].Descriptor()
}

func (GetValueResponse_Outcome) Type() protoreflect.EnumType {
	return &file_llvm_kv_compilation_caching_kv_proto_enumTypes[0]
}

func (x GetValueResponse_Outcome) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use GetValueResponse_Outcome.Descriptor instead.
func (GetValueResponse_Outcome) EnumDescriptor() ([]byte, []int) {
	return file_llvm_kv_compilation_caching_kv_proto_rawDescGZIP(), []int{2, 0}
}

type Value struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Entries       map[string][]byte      `protobuf:"bytes,1,rep,name=entries,proto3" json:"entries,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Value) Reset() {
	*x = Value{}
	mi := &file_llvm_kv_compilation_caching_kv_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Value) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Value) ProtoMessage() {}

func (x *Value) ProtoReflect() protoreflect.Message {
	mi := &file_llvm_kv_compilation_caching_kv_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Value.ProtoReflect.Descriptor instead.
func (*Value) Descriptor() ([]byte, []int) {
	return file_llvm_kv_compilation_caching_kv_proto_rawDescGZIP(), []int{0}
}

func (x *Value) GetEntries() map[string][]byte {
	if x != nil {
		return x.Entries
	}
	return nil
}

type GetValueRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           []byte                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetValueRequest) Reset() {
	*x = GetValueRequest{}
	mi := &file_llvm_kv_compilation_caching_kv_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetValueRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetValueRequest) ProtoMessage() {}

func (x *GetValueRequest) ProtoReflect() protoreflect.Message {
	mi := &file_llvm_kv_compilation_caching_kv_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetValueRequest.ProtoReflect.Descriptor instead.
func (*GetValueRequest) Descriptor() ([]byte, []int) {
	return file_llvm_kv_compilation_caching_kv_proto_rawDescGZIP(), []int{1}
}

func (x *GetValueRequest) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}

type GetValueResponse struct {
	state   protoimpl.MessageState   `protogen:"open.v1"`
	Outcome GetValueResponse_Outcome `protobuf:"varint,1,opt,name=outcome,proto3,enum=compilation_cache_service.keyvalue.v1.GetValueResponse_Outcome" json:"outcome,omitempty"`
	// Types that are valid to be assigned to Contents:
	//
	//	*GetValueResponse_Error
	//	*GetValueResponse_Value
	Contents      isGetValueResponse_Contents `protobuf_oneof:"contents"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetValueResponse) Reset() {
	*x = GetValueResponse{}
	mi := &file_llvm_kv_compilation_caching_kv_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetValueResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetValueResponse) ProtoMessage() {}

func (x *GetValueResponse) ProtoReflect() protoreflect.Message {
	mi := &file_llvm_kv_compilation_caching_kv_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetValueResponse.ProtoReflect.Descriptor instead.
func (*GetValueResponse) Descriptor() ([]byte, []int) {
	return file_llvm_kv_compilation_caching_kv_proto_rawDescGZIP(), []int{2}
}

func (x *GetValueResponse) GetOutcome() GetValueResponse_Outcome {
	if x != nil {
		return x.Outcome
	}
	return GetValueResponse_ERROR
}

func (x *GetValueResponse) GetContents() isGetValueResponse_Contents {
	if x != nil {
		return x.Contents
	}
	return nil
}

func (x *GetValueResponse) GetError() *ResponseError {
	if x != nil {
		if x, ok := x.Contents.(*GetValueResponse_Error); ok {
			return x.Error
		}
	}
	return nil
}

func (x *GetValueResponse) GetValue() *Value {
	if x != nil {
		if x, ok := x.Contents.(*GetValueResponse_Value); ok {
			return x.Value
		}
	}
	return nil
}

type isGetValueResponse_Contents interface {
	isGetValueResponse_Contents()
}

type GetValueResponse_Error struct {
	Error *ResponseError `protobuf:"bytes,2,opt,name=error,proto3,oneof"`
}

type GetValueResponse_Value struct {
	Value *Value `protobuf:"bytes,3,opt,name=value,proto3,oneof"`
}

func (*GetValueResponse_Error) isGetValueResponse_Contents() {}

func (*GetValueResponse_Value) isGetValueResponse_Contents() {}

type PutValueRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           []byte                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value         *Value                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PutValueRequest) Reset() {
	*x = PutValueRequest{}
	mi := &file_llvm_kv_compilation_caching_kv_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PutValueRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PutValueRequest) ProtoMessage() {}

func (x *PutValueRequest) ProtoReflect() protoreflect.Message {
	mi := &file_llvm_kv_compilation_caching_kv_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PutValueRequest.ProtoReflect.Descriptor instead.
func (*PutValueRequest) Descriptor() ([]byte, []int) {
	return file_llvm_kv_compilation_caching_kv_proto_rawDescGZIP(), []int{3}
}

func (x *PutValueRequest) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}

func (x *PutValueRequest) GetValue() *Value {
	if x != nil {
		return x.Value
	}
	return nil
}

type PutValueResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Error         *ResponseError         `protobuf:"bytes,1,opt,name=error,proto3,oneof" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PutValueResponse) Reset() {
	*x = PutValueResponse{}
	mi := &file_llvm_kv_compilation_caching_kv_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PutValueResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PutValueResponse) ProtoMessage() {}

func (x *PutValueResponse) ProtoReflect() protoreflect.Message {
	mi := &file_llvm_kv_compilation_caching_kv_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PutValueResponse.ProtoReflect.Descriptor instead.
func (*PutValueResponse) Descriptor() ([]byte, []int) {
	return file_llvm_kv_compilation_caching_kv_proto_rawDescGZIP(), []int{4}
}

func (x *PutValueResponse) GetError() *ResponseError {
	if x != nil {
		return x.Error
	}
	return nil
}

type ResponseError struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Description   string                 `protobuf:"bytes,1,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResponseError) Reset() {
	*x = ResponseError{}
	mi := &file_llvm_kv_compilation_caching_kv_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResponseError) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResponseError) ProtoMessage() {}

func (x *ResponseError) ProtoReflect() protoreflect.Message {
	mi := &file_llvm_kv_compilation_caching_kv_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResponseError.ProtoReflect.Descriptor instead.
func (*ResponseError) Descriptor() ([]byte, []int) {
	return file_llvm_kv_compilation_caching_kv_proto_rawDescGZIP(), []int{5}
}

func (x *ResponseError) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

var File_llvm_kv_compilation_caching_kv_proto protoreflect.FileDescriptor

const file_llvm_kv_compilation_caching_kv_proto_rawDesc = "" +
	"\n" +
	"$llvm/kv/compilation_caching_kv.proto\x12%compilation_cache_service.keyvalue.v1\"\x98\x01\n" +
	"\x05Value\x12S\n" +
	"\aentries\x18\x01 \x03(\v29.compilation_cache_service.keyvalue.v1.Value.EntriesEntryR\aentries\x1a:\n" +
	"\fEntriesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\fR\x05value:\x028\x01\"#\n" +
	"\x0fGetValueRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\fR\x03key\"\xc3\x02\n" +
	"\x10GetValueResponse\x12Y\n" +
	"\aoutcome\x18\x01 \x01(\x0e2?.compilation_cache_service.keyvalue.v1.GetValueResponse.OutcomeR\aoutcome\x12L\n" +
	"\x05error\x18\x02 \x01(\v24.compilation_cache_service.keyvalue.v1.ResponseErrorH\x00R\x05error\x12D\n" +
	"\x05value\x18\x03 \x01(\v2,.compilation_cache_service.keyvalue.v1.ValueH\x00R\x05value\"4\n" +
	"\aOutcome\x12\t\n" +
	"\x05ERROR\x10\x00\x12\x11\n" +
	"\rKEY_NOT_FOUND\x10\x01\x12\v\n" +
	"\aSUCCESS\x10\x02B\n" +
	"\n" +
	"\bcontents\"g\n" +
	"\x0fPutValueRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\fR\x03key\x12B\n" +
	"\x05value\x18\x02 \x01(\v2,.compilation_cache_service.keyvalue.v1.ValueR\x05value\"m\n" +
	"\x10PutValueResponse\x12O\n" +
	"\x05error\x18\x01 \x01(\v24.compilation_cache_service.keyvalue.v1.ResponseErrorH\x00R\x05error\x88\x01\x01B\b\n" +
	"\x06_error\"1\n" +
	"\rResponseError\x12 \n" +
	"\vdescription\x18\x01 \x01(\tR\vdescription2\x8a\x02\n" +
	"\n" +
	"KeyValueDB\x12}\n" +
	"\bGetValue\x126.compilation_cache_service.keyvalue.v1.GetValueRequest\x1a7.compilation_cache_service.keyvalue.v1.GetValueResponse\"\x00\x12}\n" +
	"\bPutValue\x126.compilation_cache_service.keyvalue.v1.PutValueRequest\x1a7.compilation_cache_service.keyvalue.v1.PutValueResponse\"\x00B\x87\x01\n" +
	"&com.apple.dt.compilation_cache_serviceB\x17CompilationCachingProtoP\x01Z<github.com/bitrise-io/bitrise-build-cache-cli/llvm/kv;llvmkv\xa2\x02\x03CCSb\x06proto3"

var (
	file_llvm_kv_compilation_caching_kv_proto_rawDescOnce sync.Once
	file_llvm_kv_compilation_caching_kv_proto_rawDescData []byte
)

func file_llvm_kv_compilation_caching_kv_proto_rawDescGZIP() []byte {
	file_llvm_kv_compilation_caching_kv_proto_rawDescOnce.Do(func() {
		file_llvm_kv_compilation_caching_kv_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_llvm_kv_compilation_caching_kv_proto_rawDesc), len(file_llvm_kv_compilation_caching_kv_proto_rawDesc)))
	})
	return file_llvm_kv_compilation_caching_kv_proto_rawDescData
}

var file_llvm_kv_compilation_caching_kv_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_llvm_kv_compilation_caching_kv_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_llvm_kv_compilation_caching_kv_proto_goTypes = []any{
	(GetValueResponse_Outcome)(0), // 0: compilation_cache_service.keyvalue.v1.GetValueResponse.Outcome
	(*Value)(nil),                 // 1: compilation_cache_service.keyvalue.v1.Value
	(*GetValueRequest)(nil),       // 2: compilation_cache_service.keyvalue.v1.GetValueRequest
	(*GetValueResponse)(nil),      // 3: compilation_cache_service.keyvalue.v1.GetValueResponse
	(*PutValueRequest)(nil),       // 4: compilation_cache_service.keyvalue.v1.PutValueRequest
	(*PutValueResponse)(nil),      // 5: compilation_cache_service.keyvalue.v1.PutValueResponse
	(*ResponseError)(nil),         // 6: compilation_cache_service.keyvalue.v1.ResponseError
	nil,                           // 7: compilation_cache_service.keyvalue.v1.Value.EntriesEntry
}
var file_llvm_kv_compilation_caching_kv_proto_depIdxs = []int32{
	7, // 0: compilation_cache_service.keyvalue.v1.Value.entries:type_name -> compilation_cache_service.keyvalue.v1.Value.EntriesEntry
	0, // 1: compilation_cache_service.keyvalue.v1.GetValueResponse.outcome:type_name -> compilation_cache_service.keyvalue.v1.GetValueResponse.Outcome
	6, // 2: compilation_cache_service.keyvalue.v1.GetValueResponse.error:type_name -> compilation_cache_service.keyvalue.v1.ResponseError
	1, // 3: compilation_cache_service.keyvalue.v1.GetValueResponse.value:type_name -> compilation_cache_service.keyvalue.v1.Value
	1, // 4: compilation_cache_service.keyvalue.v1.PutValueRequest.value:type_name -> compilation_cache_service.keyvalue.v1.Value
	6, // 5: compilation_cache_service.keyvalue.v1.PutValueResponse.error:type_name -> compilation_cache_service.keyvalue.v1.ResponseError
	2, // 6: compilation_cache_service.keyvalue.v1.KeyValueDB.GetValue:input_type -> compilation_cache_service.keyvalue.v1.GetValueRequest
	4, // 7: compilation_cache_service.keyvalue.v1.KeyValueDB.PutValue:input_type -> compilation_cache_service.keyvalue.v1.PutValueRequest
	3, // 8: compilation_cache_service.keyvalue.v1.KeyValueDB.GetValue:output_type -> compilation_cache_service.keyvalue.v1.GetValueResponse
	5, // 9: compilation_cache_service.keyvalue.v1.KeyValueDB.PutValue:output_type -> compilation_cache_service.keyvalue.v1.PutValueResponse
	8, // [8:10] is the sub-list for method output_type
	6, // [6:8] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_llvm_kv_compilation_caching_kv_proto_init() }
func file_llvm_kv_compilation_caching_kv_proto_init() {
	if File_llvm_kv_compilation_caching_kv_proto != nil {
		return
	}
	file_llvm_kv_compilation_caching_kv_proto_msgTypes[2].OneofWrappers = []any{
		(*GetValueResponse_Error)(nil),
		(*GetValueResponse_Value)(nil),
	}
	file_llvm_kv_compilation_caching_kv_proto_msgTypes[4].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_llvm_kv_compilation_caching_kv_proto_rawDesc), len(file_llvm_kv_compilation_caching_kv_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_llvm_kv_compilation_caching_kv_proto_goTypes,
		DependencyIndexes: file_llvm_kv_compilation_caching_kv_proto_depIdxs,
		EnumInfos:         file_llvm_kv_compilation_caching_kv_proto_enumTypes,
		MessageInfos:      file_llvm_kv_compilation_caching_kv_proto_msgTypes,
	}.Build()
	File_llvm_kv_compilation_caching_kv_proto = out.File
	file_llvm_kv_compilation_caching_kv_proto_goTypes = nil
	file_llvm_kv_compilation_caching_kv_proto_depIdxs = nil
}
