#!/bin/sh
# Generated by `bitrise-build-cache bazel install-credhelper-shim`.
# Do not edit by hand — regenerate with the same command to pick up a new pin.
#
# Bazel invokes this script per --credential_helper protocol. It locates
# `bitrise-build-cache` on PATH, or downloads it into a workspace-local cache
# and then execs it with the passed arguments.
set -eu

BITRISE_BUILD_CACHE_VERSION="__BITRISE_BUILD_CACHE_VERSION__"

script_dir="$(cd "$(dirname "$0")" && pwd)"
# The shim lives at <workspace>/tools/... by convention; the workspace root is
# the parent of its containing dir. Callers overriding --dir must keep the
# shim one level deep, or set BITRISE_BUILD_CACHE_WORKSPACE_ROOT.
workspace_root="${BITRISE_BUILD_CACHE_WORKSPACE_ROOT:-$(cd "${script_dir}/.." && pwd)}"
cache_bin="${workspace_root}/.bitrise-cache/bin"
cached_cli="${cache_bin}/bitrise-build-cache"

if command -v bitrise-build-cache >/dev/null 2>&1; then
  exec bitrise-build-cache "$@"
fi

if [ -x "${cached_cli}" ]; then
  exec "${cached_cli}" "$@"
fi

mkdir -p "${cache_bin}"

installer_ref="${BITRISE_BUILD_CACHE_VERSION}"
if [ -z "${installer_ref}" ] || [ "${installer_ref}" = "latest" ]; then
  installer_ref="main"
fi
installer_url="https://raw.githubusercontent.com/bitrise-io/bitrise-build-cache-cli/${installer_ref}/install/installer.sh"

fetch() {
  if command -v curl >/dev/null 2>&1; then
    curl --retry 5 -sSfL "$1"
  elif command -v wget >/dev/null 2>&1; then
    wget -qO- "$1"
  else
    echo "bitrise-build-cache-credhelper: neither curl nor wget is installed" >&2

    return 1
  fi
}

# Bazel spawns credential helpers in parallel (loading_phase_threads). Serialise
# the install so concurrent shims cannot stomp each other's writes on cold
# cache. Losers of the race fall through to `exec` the winner's binary.
install_cli() {
  install_tmp="${cache_bin}/.install.$$.tmp"
  rm -rf "${install_tmp}"
  mkdir -p "${install_tmp}"

  installer_body="$(fetch "${installer_url}")" || {
    echo "bitrise-build-cache-credhelper: failed to download installer from ${installer_url}" >&2
    echo "Install bitrise-build-cache manually: https://github.com/bitrise-io/bitrise-build-cache-cli" >&2
    rm -rf "${install_tmp}"

    return 1
  }

  install_args="-b ${install_tmp}"
  if [ -n "${BITRISE_BUILD_CACHE_VERSION}" ] && [ "${BITRISE_BUILD_CACHE_VERSION}" != "latest" ]; then
    install_args="${install_args} ${BITRISE_BUILD_CACHE_VERSION}"
  fi

  # shellcheck disable=SC2086
  if ! printf '%s' "${installer_body}" | sh -s -- ${install_args} >&2; then
    echo "bitrise-build-cache-credhelper: installer.sh failed" >&2
    rm -rf "${install_tmp}"

    return 1
  fi

  if [ ! -x "${install_tmp}/bitrise-build-cache" ]; then
    echo "bitrise-build-cache-credhelper: installer ran but ${install_tmp}/bitrise-build-cache is missing" >&2
    rm -rf "${install_tmp}"

    return 1
  fi

  mv -f "${install_tmp}/bitrise-build-cache" "${cached_cli}"
  rm -rf "${install_tmp}"
}

lockfile="${cache_bin}/.install.lock"
: > "${lockfile}" 2>/dev/null || true

if command -v flock >/dev/null 2>&1; then
  (
    flock -x 9 || exit 1
    if [ -x "${cached_cli}" ]; then
      exit 0
    fi
    install_cli
  ) 9>"${lockfile}" || exit 1
else
  # Portable fallback: mkdir spinlock. Cap the wait so a stale lockdir cannot
  # hang the build forever; the loser rechecks the cached binary anyway.
  spinlock_dir="${cache_bin}/.install.spinlock"
  i=0
  while ! mkdir "${spinlock_dir}" 2>/dev/null; do
    if [ -x "${cached_cli}" ]; then
      break
    fi
    i=$((i + 1))
    if [ "${i}" -gt 300 ]; then
      # ~30s: assume a dead process, break the lock and try ourselves.
      rmdir "${spinlock_dir}" 2>/dev/null || true

      continue
    fi
    sleep 0.1
  done
  if [ ! -x "${cached_cli}" ]; then
    trap 'rmdir "${spinlock_dir}" 2>/dev/null || true' EXIT
    install_cli || {
      rmdir "${spinlock_dir}" 2>/dev/null || true
      exit 1
    }
  fi
  rmdir "${spinlock_dir}" 2>/dev/null || true
fi

if [ ! -x "${cached_cli}" ]; then
  echo "bitrise-build-cache-credhelper: install completed but ${cached_cli} is missing" >&2
  exit 1
fi

exec "${cached_cli}" "$@"
