#!/bin/sh
# Generated by `bitrise-build-cache bazel install-credhelper-shim`.
# Do not edit by hand — regenerate with the same command to pick up a new pin.
#
# Bazel invokes this script per --credential_helper protocol. It locates
# `bitrise-build-cache` on PATH, or downloads it into a workspace-local cache
# and then execs it with the passed arguments.
set -eu

BITRISE_BUILD_CACHE_VERSION="__BITRISE_BUILD_CACHE_VERSION__"

script_dir="$(cd "$(dirname "$0")" && pwd)"
# The shim lives at <workspace>/tools/... by convention; the workspace root is
# the parent of its containing dir. Callers overriding --dir must keep the
# shim one level deep, or set BITRISE_BUILD_CACHE_WORKSPACE_ROOT.
workspace_root="${BITRISE_BUILD_CACHE_WORKSPACE_ROOT:-$(cd "${script_dir}/.." && pwd)}"
cache_bin="${workspace_root}/.bitrise-cache/bin"
cached_cli="${cache_bin}/bitrise-build-cache"

if command -v bitrise-build-cache >/dev/null 2>&1; then
  exec bitrise-build-cache "$@"
fi

if [ -x "${cached_cli}" ]; then
  exec "${cached_cli}" "$@"
fi

mkdir -p "${cache_bin}"

installer_ref="${BITRISE_BUILD_CACHE_VERSION}"
if [ -z "${installer_ref}" ] || [ "${installer_ref}" = "latest" ]; then
  installer_ref="main"
fi
installer_url="https://raw.githubusercontent.com/bitrise-io/bitrise-build-cache-cli/${installer_ref}/install/installer.sh"

fetch() {
  if command -v curl >/dev/null 2>&1; then
    curl --retry 5 -sSfL "$1"
  elif command -v wget >/dev/null 2>&1; then
    wget -qO- "$1"
  else
    echo "bitrise-build-cache-credhelper: neither curl nor wget is installed" >&2

    return 1
  fi
}

installer_body="$(fetch "${installer_url}")" || {
  echo "bitrise-build-cache-credhelper: failed to download installer from ${installer_url}" >&2
  echo "Install bitrise-build-cache manually: https://github.com/bitrise-io/bitrise-build-cache-cli" >&2
  exit 1
}

install_args="-b ${cache_bin}"
if [ -n "${BITRISE_BUILD_CACHE_VERSION}" ] && [ "${BITRISE_BUILD_CACHE_VERSION}" != "latest" ]; then
  install_args="${install_args} ${BITRISE_BUILD_CACHE_VERSION}"
fi

# shellcheck disable=SC2086
if ! printf '%s' "${installer_body}" | sh -s -- ${install_args} >&2; then
  echo "bitrise-build-cache-credhelper: installer.sh failed" >&2
  exit 1
fi

if [ ! -x "${cached_cli}" ]; then
  echo "bitrise-build-cache-credhelper: installer ran but ${cached_cli} is missing" >&2
  exit 1
fi

exec "${cached_cli}" "$@"
