// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package mocks

import (
	"sync"

	"github.com/bitrise-io/xcelerate/internal/xcodeargs"
)

// Ensure, that XcodeArgsMock does implement xcodeargs.XcodeArgs.
// If this is not the case, regenerate this file with moq.
var _ xcodeargs.XcodeArgs = &XcodeArgsMock{}

// XcodeArgsMock is a mock implementation of xcodeargs.XcodeArgs.
//
//	func TestSomethingThatUsesXcodeArgs(t *testing.T) {
//
//		// make and configure a mocked xcodeargs.XcodeArgs
//		mockedXcodeArgs := &XcodeArgsMock{
//			ArgsFunc: func() []string {
//				panic("mock out the Args method")
//			},
//		}
//
//		// use mockedXcodeArgs in code that requires xcodeargs.XcodeArgs
//		// and then make assertions.
//
//	}
type XcodeArgsMock struct {
	// ArgsFunc mocks the Args method.
	ArgsFunc func() []string

	// calls tracks calls to the methods.
	calls struct {
		// Args holds details about calls to the Args method.
		Args []struct {
		}
	}
	lockArgs sync.RWMutex
}

// Args calls ArgsFunc.
func (mock *XcodeArgsMock) Args() []string {
	if mock.ArgsFunc == nil {
		panic("XcodeArgsMock.ArgsFunc: method is nil but XcodeArgs.Args was just called")
	}
	callInfo := struct {
	}{}
	mock.lockArgs.Lock()
	mock.calls.Args = append(mock.calls.Args, callInfo)
	mock.lockArgs.Unlock()
	return mock.ArgsFunc()
}

// ArgsCalls gets all the calls that were made to Args.
// Check the length with:
//
//	len(mockedXcodeArgs.ArgsCalls())
func (mock *XcodeArgsMock) ArgsCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockArgs.RLock()
	calls = mock.calls.Args
	mock.lockArgs.RUnlock()
	return calls
}
