// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package ccache

import (
	"context"
	"io"
	"sync"
)

// Ensure, that ClientMock does implement Client.
// If this is not the case, regenerate this file with moq.
var _ Client = &ClientMock{}

// ClientMock is a mock implementation of Client.
//
//	func TestSomethingThatUsesClient(t *testing.T) {
//
//		// make and configure a mocked Client
//		mockedClient := &ClientMock{
//			DownloadStreamFunc: func(ctx context.Context, writer io.Writer, key string) error {
//				panic("mock out the DownloadStream method")
//			},
//			GetCapabilitiesWithRetryFunc: func(ctx context.Context) error {
//				panic("mock out the GetCapabilitiesWithRetry method")
//			},
//			UploadStreamToBuildCacheFunc: func(ctx context.Context, reader io.ReadSeeker, key string, size int64) error {
//				panic("mock out the UploadStreamToBuildCache method")
//			},
//		}
//
//		// use mockedClient in code that requires Client
//		// and then make assertions.
//
//	}
type ClientMock struct {
	// DownloadStreamFunc mocks the DownloadStream method.
	DownloadStreamFunc func(ctx context.Context, writer io.Writer, key string) error

	// GetCapabilitiesWithRetryFunc mocks the GetCapabilitiesWithRetry method.
	GetCapabilitiesWithRetryFunc func(ctx context.Context) error

	// UploadStreamToBuildCacheFunc mocks the UploadStreamToBuildCache method.
	UploadStreamToBuildCacheFunc func(ctx context.Context, reader io.ReadSeeker, key string, size int64) error

	// calls tracks calls to the methods.
	calls struct {
		// DownloadStream holds details about calls to the DownloadStream method.
		DownloadStream []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Writer is the writer argument value.
			Writer io.Writer
			// Key is the key argument value.
			Key string
		}
		// GetCapabilitiesWithRetry holds details about calls to the GetCapabilitiesWithRetry method.
		GetCapabilitiesWithRetry []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
		}
		// UploadStreamToBuildCache holds details about calls to the UploadStreamToBuildCache method.
		UploadStreamToBuildCache []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Reader is the reader argument value.
			Reader io.ReadSeeker
			// Key is the key argument value.
			Key string
			// Size is the size argument value.
			Size int64
		}
	}
	lockDownloadStream           sync.RWMutex
	lockGetCapabilitiesWithRetry sync.RWMutex
	lockUploadStreamToBuildCache sync.RWMutex
}

// DownloadStream calls DownloadStreamFunc.
func (mock *ClientMock) DownloadStream(ctx context.Context, writer io.Writer, key string) error {
	callInfo := struct {
		Ctx    context.Context
		Writer io.Writer
		Key    string
	}{
		Ctx:    ctx,
		Writer: writer,
		Key:    key,
	}
	mock.lockDownloadStream.Lock()
	mock.calls.DownloadStream = append(mock.calls.DownloadStream, callInfo)
	mock.lockDownloadStream.Unlock()
	if mock.DownloadStreamFunc == nil {
		var (
			errOut error
		)
		return errOut
	}
	return mock.DownloadStreamFunc(ctx, writer, key)
}

// DownloadStreamCalls gets all the calls that were made to DownloadStream.
// Check the length with:
//
//	len(mockedClient.DownloadStreamCalls())
func (mock *ClientMock) DownloadStreamCalls() []struct {
	Ctx    context.Context
	Writer io.Writer
	Key    string
} {
	var calls []struct {
		Ctx    context.Context
		Writer io.Writer
		Key    string
	}
	mock.lockDownloadStream.RLock()
	calls = mock.calls.DownloadStream
	mock.lockDownloadStream.RUnlock()
	return calls
}

// GetCapabilitiesWithRetry calls GetCapabilitiesWithRetryFunc.
func (mock *ClientMock) GetCapabilitiesWithRetry(ctx context.Context) error {
	callInfo := struct {
		Ctx context.Context
	}{
		Ctx: ctx,
	}
	mock.lockGetCapabilitiesWithRetry.Lock()
	mock.calls.GetCapabilitiesWithRetry = append(mock.calls.GetCapabilitiesWithRetry, callInfo)
	mock.lockGetCapabilitiesWithRetry.Unlock()
	if mock.GetCapabilitiesWithRetryFunc == nil {
		var (
			errOut error
		)
		return errOut
	}
	return mock.GetCapabilitiesWithRetryFunc(ctx)
}

// GetCapabilitiesWithRetryCalls gets all the calls that were made to GetCapabilitiesWithRetry.
// Check the length with:
//
//	len(mockedClient.GetCapabilitiesWithRetryCalls())
func (mock *ClientMock) GetCapabilitiesWithRetryCalls() []struct {
	Ctx context.Context
} {
	var calls []struct {
		Ctx context.Context
	}
	mock.lockGetCapabilitiesWithRetry.RLock()
	calls = mock.calls.GetCapabilitiesWithRetry
	mock.lockGetCapabilitiesWithRetry.RUnlock()
	return calls
}

// UploadStreamToBuildCache calls UploadStreamToBuildCacheFunc.
func (mock *ClientMock) UploadStreamToBuildCache(ctx context.Context, reader io.ReadSeeker, key string, size int64) error {
	callInfo := struct {
		Ctx    context.Context
		Reader io.ReadSeeker
		Key    string
		Size   int64
	}{
		Ctx:    ctx,
		Reader: reader,
		Key:    key,
		Size:   size,
	}
	mock.lockUploadStreamToBuildCache.Lock()
	mock.calls.UploadStreamToBuildCache = append(mock.calls.UploadStreamToBuildCache, callInfo)
	mock.lockUploadStreamToBuildCache.Unlock()
	if mock.UploadStreamToBuildCacheFunc == nil {
		var (
			errOut error
		)
		return errOut
	}
	return mock.UploadStreamToBuildCacheFunc(ctx, reader, key, size)
}

// UploadStreamToBuildCacheCalls gets all the calls that were made to UploadStreamToBuildCache.
// Check the length with:
//
//	len(mockedClient.UploadStreamToBuildCacheCalls())
func (mock *ClientMock) UploadStreamToBuildCacheCalls() []struct {
	Ctx    context.Context
	Reader io.ReadSeeker
	Key    string
	Size   int64
} {
	var calls []struct {
		Ctx    context.Context
		Reader io.ReadSeeker
		Key    string
		Size   int64
	}
	mock.lockUploadStreamToBuildCache.RLock()
	calls = mock.calls.UploadStreamToBuildCache
	mock.lockUploadStreamToBuildCache.RUnlock()
	return calls
}
