// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package mocks

import (
	"github.com/bitrise-io/bitrise-build-cache-cli/cmd"
	"os"
	"sync"
	"syscall"
)

// Ensure, that CommandMock does implement cmd.Command.
// If this is not the case, regenerate this file with moq.
var _ cmd.Command = &CommandMock{}

// CommandMock is a mock implementation of cmd.Command.
//
//	func TestSomethingThatUsesCommand(t *testing.T) {
//
//		// make and configure a mocked cmd.Command
//		mockedCommand := &CommandMock{
//			PIDFunc: func() int {
//				panic("mock out the PID method")
//			},
//			SetStderrFunc: func(file *os.File)  {
//				panic("mock out the SetStderr method")
//			},
//			SetStdinFunc: func(file *os.File)  {
//				panic("mock out the SetStdin method")
//			},
//			SetStdoutFunc: func(file *os.File)  {
//				panic("mock out the SetStdout method")
//			},
//			SetSysProcAttrFunc: func(sysProcAttr *syscall.SysProcAttr)  {
//				panic("mock out the SetSysProcAttr method")
//			},
//			StartFunc: func() error {
//				panic("mock out the Start method")
//			},
//		}
//
//		// use mockedCommand in code that requires cmd.Command
//		// and then make assertions.
//
//	}
type CommandMock struct {
	// PIDFunc mocks the PID method.
	PIDFunc func() int

	// SetStderrFunc mocks the SetStderr method.
	SetStderrFunc func(file *os.File)

	// SetStdinFunc mocks the SetStdin method.
	SetStdinFunc func(file *os.File)

	// SetStdoutFunc mocks the SetStdout method.
	SetStdoutFunc func(file *os.File)

	// SetSysProcAttrFunc mocks the SetSysProcAttr method.
	SetSysProcAttrFunc func(sysProcAttr *syscall.SysProcAttr)

	// StartFunc mocks the Start method.
	StartFunc func() error

	// calls tracks calls to the methods.
	calls struct {
		// PID holds details about calls to the PID method.
		PID []struct {
		}
		// SetStderr holds details about calls to the SetStderr method.
		SetStderr []struct {
			// File is the file argument value.
			File *os.File
		}
		// SetStdin holds details about calls to the SetStdin method.
		SetStdin []struct {
			// File is the file argument value.
			File *os.File
		}
		// SetStdout holds details about calls to the SetStdout method.
		SetStdout []struct {
			// File is the file argument value.
			File *os.File
		}
		// SetSysProcAttr holds details about calls to the SetSysProcAttr method.
		SetSysProcAttr []struct {
			// SysProcAttr is the sysProcAttr argument value.
			SysProcAttr *syscall.SysProcAttr
		}
		// Start holds details about calls to the Start method.
		Start []struct {
		}
	}
	lockPID            sync.RWMutex
	lockSetStderr      sync.RWMutex
	lockSetStdin       sync.RWMutex
	lockSetStdout      sync.RWMutex
	lockSetSysProcAttr sync.RWMutex
	lockStart          sync.RWMutex
}

// PID calls PIDFunc.
func (mock *CommandMock) PID() int {
	if mock.PIDFunc == nil {
		panic("CommandMock.PIDFunc: method is nil but Command.PID was just called")
	}
	callInfo := struct {
	}{}
	mock.lockPID.Lock()
	mock.calls.PID = append(mock.calls.PID, callInfo)
	mock.lockPID.Unlock()
	return mock.PIDFunc()
}

// PIDCalls gets all the calls that were made to PID.
// Check the length with:
//
//	len(mockedCommand.PIDCalls())
func (mock *CommandMock) PIDCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockPID.RLock()
	calls = mock.calls.PID
	mock.lockPID.RUnlock()
	return calls
}

// SetStderr calls SetStderrFunc.
func (mock *CommandMock) SetStderr(file *os.File) {
	if mock.SetStderrFunc == nil {
		panic("CommandMock.SetStderrFunc: method is nil but Command.SetStderr was just called")
	}
	callInfo := struct {
		File *os.File
	}{
		File: file,
	}
	mock.lockSetStderr.Lock()
	mock.calls.SetStderr = append(mock.calls.SetStderr, callInfo)
	mock.lockSetStderr.Unlock()
	mock.SetStderrFunc(file)
}

// SetStderrCalls gets all the calls that were made to SetStderr.
// Check the length with:
//
//	len(mockedCommand.SetStderrCalls())
func (mock *CommandMock) SetStderrCalls() []struct {
	File *os.File
} {
	var calls []struct {
		File *os.File
	}
	mock.lockSetStderr.RLock()
	calls = mock.calls.SetStderr
	mock.lockSetStderr.RUnlock()
	return calls
}

// SetStdin calls SetStdinFunc.
func (mock *CommandMock) SetStdin(file *os.File) {
	if mock.SetStdinFunc == nil {
		panic("CommandMock.SetStdinFunc: method is nil but Command.SetStdin was just called")
	}
	callInfo := struct {
		File *os.File
	}{
		File: file,
	}
	mock.lockSetStdin.Lock()
	mock.calls.SetStdin = append(mock.calls.SetStdin, callInfo)
	mock.lockSetStdin.Unlock()
	mock.SetStdinFunc(file)
}

// SetStdinCalls gets all the calls that were made to SetStdin.
// Check the length with:
//
//	len(mockedCommand.SetStdinCalls())
func (mock *CommandMock) SetStdinCalls() []struct {
	File *os.File
} {
	var calls []struct {
		File *os.File
	}
	mock.lockSetStdin.RLock()
	calls = mock.calls.SetStdin
	mock.lockSetStdin.RUnlock()
	return calls
}

// SetStdout calls SetStdoutFunc.
func (mock *CommandMock) SetStdout(file *os.File) {
	if mock.SetStdoutFunc == nil {
		panic("CommandMock.SetStdoutFunc: method is nil but Command.SetStdout was just called")
	}
	callInfo := struct {
		File *os.File
	}{
		File: file,
	}
	mock.lockSetStdout.Lock()
	mock.calls.SetStdout = append(mock.calls.SetStdout, callInfo)
	mock.lockSetStdout.Unlock()
	mock.SetStdoutFunc(file)
}

// SetStdoutCalls gets all the calls that were made to SetStdout.
// Check the length with:
//
//	len(mockedCommand.SetStdoutCalls())
func (mock *CommandMock) SetStdoutCalls() []struct {
	File *os.File
} {
	var calls []struct {
		File *os.File
	}
	mock.lockSetStdout.RLock()
	calls = mock.calls.SetStdout
	mock.lockSetStdout.RUnlock()
	return calls
}

// SetSysProcAttr calls SetSysProcAttrFunc.
func (mock *CommandMock) SetSysProcAttr(sysProcAttr *syscall.SysProcAttr) {
	if mock.SetSysProcAttrFunc == nil {
		panic("CommandMock.SetSysProcAttrFunc: method is nil but Command.SetSysProcAttr was just called")
	}
	callInfo := struct {
		SysProcAttr *syscall.SysProcAttr
	}{
		SysProcAttr: sysProcAttr,
	}
	mock.lockSetSysProcAttr.Lock()
	mock.calls.SetSysProcAttr = append(mock.calls.SetSysProcAttr, callInfo)
	mock.lockSetSysProcAttr.Unlock()
	mock.SetSysProcAttrFunc(sysProcAttr)
}

// SetSysProcAttrCalls gets all the calls that were made to SetSysProcAttr.
// Check the length with:
//
//	len(mockedCommand.SetSysProcAttrCalls())
func (mock *CommandMock) SetSysProcAttrCalls() []struct {
	SysProcAttr *syscall.SysProcAttr
} {
	var calls []struct {
		SysProcAttr *syscall.SysProcAttr
	}
	mock.lockSetSysProcAttr.RLock()
	calls = mock.calls.SetSysProcAttr
	mock.lockSetSysProcAttr.RUnlock()
	return calls
}

// Start calls StartFunc.
func (mock *CommandMock) Start() error {
	if mock.StartFunc == nil {
		panic("CommandMock.StartFunc: method is nil but Command.Start was just called")
	}
	callInfo := struct {
	}{}
	mock.lockStart.Lock()
	mock.calls.Start = append(mock.calls.Start, callInfo)
	mock.lockStart.Unlock()
	return mock.StartFunc()
}

// StartCalls gets all the calls that were made to Start.
// Check the length with:
//
//	len(mockedCommand.StartCalls())
func (mock *CommandMock) StartCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockStart.RLock()
	calls = mock.calls.Start
	mock.lockStart.RUnlock()
	return calls
}
