// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package enrichment_test

import (
	"github.com/bitrise-io/bitrise-build-cache-cli/v3/internal/xcelerate/analytics"
	"github.com/bitrise-io/bitrise-build-cache-cli/v3/internal/xcelerate/enrichment"
	"sync"
)

// Ensure, that InvocationPutterMock does implement enrichment.InvocationPutter.
// If this is not the case, regenerate this file with moq.
var _ enrichment.InvocationPutter = &InvocationPutterMock{}

// InvocationPutterMock is a mock implementation of enrichment.InvocationPutter.
//
//	func TestSomethingThatUsesInvocationPutter(t *testing.T) {
//
//		// make and configure a mocked enrichment.InvocationPutter
//		mockedInvocationPutter := &InvocationPutterMock{
//			PutInvocationFunc: func(inv analytics.Invocation) error {
//				panic("mock out the PutInvocation method")
//			},
//		}
//
//		// use mockedInvocationPutter in code that requires enrichment.InvocationPutter
//		// and then make assertions.
//
//	}
type InvocationPutterMock struct {
	// PutInvocationFunc mocks the PutInvocation method.
	PutInvocationFunc func(inv analytics.Invocation) error

	// calls tracks calls to the methods.
	calls struct {
		// PutInvocation holds details about calls to the PutInvocation method.
		PutInvocation []struct {
			// Inv is the inv argument value.
			Inv analytics.Invocation
		}
	}
	lockPutInvocation sync.RWMutex
}

// PutInvocation calls PutInvocationFunc.
func (mock *InvocationPutterMock) PutInvocation(inv analytics.Invocation) error {
	callInfo := struct {
		Inv analytics.Invocation
	}{
		Inv: inv,
	}
	mock.lockPutInvocation.Lock()
	mock.calls.PutInvocation = append(mock.calls.PutInvocation, callInfo)
	mock.lockPutInvocation.Unlock()
	if mock.PutInvocationFunc == nil {
		var (
			errOut error
		)
		return errOut
	}
	return mock.PutInvocationFunc(inv)
}

// PutInvocationCalls gets all the calls that were made to PutInvocation.
// Check the length with:
//
//	len(mockedInvocationPutter.PutInvocationCalls())
func (mock *InvocationPutterMock) PutInvocationCalls() []struct {
	Inv analytics.Invocation
} {
	var calls []struct {
		Inv analytics.Invocation
	}
	mock.lockPutInvocation.RLock()
	calls = mock.calls.PutInvocation
	mock.lockPutInvocation.RUnlock()
	return calls
}
